"""Generate PyMOL scripts (.pml) rendering PTM sites colored by log2-fold-change."""

from __future__ import annotations

from pathlib import Path

import polars as pl

_LOG2FC_COLOR_SCALE = 2.0
_SIGNIFICANT_FDR = 0.05


def _fold_change_rgb(log2fc: float) -> tuple[float, float, float]:
    """Map a log2FC value onto a green-white-red gradient as RGB in [0, 1]."""
    intensity = min(1.0, abs(log2fc) / _LOG2FC_COLOR_SCALE)
    if log2fc > 0:
        return 1.0, 1.0 - intensity, 1.0 - intensity
    return 1.0 - intensity, 1.0, 1.0 - intensity


def generate_pymol_script(
    pdb_path: Path | str,
    ptm_df: pl.DataFrame,
    output_pml_path: Path | str,
    protein_name: str = "Protein",
    contrast_name: str = "Comparison",
) -> Path:
    """Write a PyMOL script rendering the structure with log2FC-colored PTM sites.

    Sites significant at FDR < 0.05 additionally get a text label.

    Args:
        pdb_path: Path to the structure file to load in PyMOL.
        ptm_df: Standardized PTM table for one protein.
        output_pml_path: Destination for the ``.pml`` script.
        protein_name: Display name used in the script header.
        contrast_name: Contrast name used in the script header.

    Returns:
        The path of the written script.
    """
    output_path = Path(output_pml_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    abs_pdb_path = Path(pdb_path).absolute()

    valid_ptms = ptm_df.drop_nulls(subset=["pos_in_protein", "log2fc"])

    lines = [
        f"# PyMOL Visualization Script for {protein_name} ({contrast_name})",
        "# Generated by proptm3d",
        "reinitialize",
        "bg_color white",
        f'load "{abs_pdb_path}", prot',
        "hide everything, prot",
        "show cartoon, prot",
        "color gray80, prot",
        "",
        "# Assign log2FC colors to PTM residues",
    ]

    for row in valid_ptms.iter_rows(named=True):
        res_num = int(row["pos_in_protein"])
        log2fc = float(row["log2fc"])
        fdr_value = row.get("fdr")
        fdr = 1.0 if fdr_value is None else float(fdr_value)
        mod_aa = str(row.get("mod_aa") or "")

        r, g, b = _fold_change_rgb(log2fc)
        color_name = f"col_ptm_{res_num}"
        lines.append(f"set_color {color_name}, [{r:.3f}, {g:.3f}, {b:.3f}]")
        lines.append(f"show spheres, prot and resi {res_num}")
        lines.append(f"color {color_name}, prot and resi {res_num}")

        if fdr < _SIGNIFICANT_FDR:
            label = f"{mod_aa}{res_num} (log2FC={log2fc:+.2f})"
            lines.append(f'label prot and resi {res_num} and name CA, "{label}"')

    lines.extend(
        [
            "",
            "set label_size, 16",
            "set label_color, black",
            "set label_font_id, 7",
            "set sphere_scale, 0.8",
            "orient prot",
            "zoom prot, 5",
            "ray 2000, 1500",
            f"# save {output_path.with_suffix('.png')}",
        ]
    )

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path
