# PyMOL Visualization Script for CIC (Comparison)
# Generated by ptm3d Visualizer
reinitialize
bg_color white
load "/Users/jonasgrossmann/GitHub/PTMvisualizer/output_3d/structures/Q96RK0.pdb", prot
hide everything, prot
show cartoon, prot
color gray80, prot

# Set up log2FC color spectrum
set b_factor_min, -2.0
set b_factor_max, 2.0

# Assign log2FC values to PTM residues
set_color col_ptm_1082, [1.000, 0.629, 0.629]
show spheres, prot and resi 1082
color col_ptm_1082, prot and resi 1082
label prot and resi 1082 and name CA, "S1082 (log2FC=+0.74)"
set_color col_ptm_1345, [1.000, 0.729, 0.729]
show spheres, prot and resi 1345
color col_ptm_1345, prot and resi 1345
set_color col_ptm_1609, [1.000, 0.946, 0.946]
show spheres, prot and resi 1609
color col_ptm_1609, prot and resi 1609
set_color col_ptm_1813, [1.000, 0.910, 0.910]
show spheres, prot and resi 1813
color col_ptm_1813, prot and resi 1813
set_color col_ptm_2082, [1.000, 0.888, 0.888]
show spheres, prot and resi 2082
color col_ptm_2082, prot and resi 2082
set_color col_ptm_2155, [1.000, 0.989, 0.989]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_2203, [1.000, 0.922, 0.922]
show spheres, prot and resi 2203
color col_ptm_2203, prot and resi 2203
set_color col_ptm_2318, [0.833, 0.833, 1.000]
show spheres, prot and resi 2318
color col_ptm_2318, prot and resi 2318
set_color col_ptm_664, [1.000, 0.810, 0.810]
show spheres, prot and resi 664
color col_ptm_664, prot and resi 664
set_color col_ptm_768, [1.000, 0.849, 0.849]
show spheres, prot and resi 768
color col_ptm_768, prot and resi 768
set_color col_ptm_809, [0.998, 0.998, 1.000]
show spheres, prot and resi 809
color col_ptm_809, prot and resi 809
set_color col_ptm_1344, [0.915, 0.915, 1.000]
show spheres, prot and resi 1344
color col_ptm_1344, prot and resi 1344
set_color col_ptm_1492, [1.000, 0.840, 0.840]
show spheres, prot and resi 1492
color col_ptm_1492, prot and resi 1492
set_color col_ptm_2227, [1.000, 0.859, 0.859]
show spheres, prot and resi 2227
color col_ptm_2227, prot and resi 2227
set_color col_ptm_472, [1.000, 0.871, 0.871]
show spheres, prot and resi 472
color col_ptm_472, prot and resi 472
set_color col_ptm_1082, [1.000, 0.948, 0.948]
show spheres, prot and resi 1082
color col_ptm_1082, prot and resi 1082
set_color col_ptm_1345, [0.977, 0.977, 1.000]
show spheres, prot and resi 1345
color col_ptm_1345, prot and resi 1345
set_color col_ptm_1609, [0.963, 0.963, 1.000]
show spheres, prot and resi 1609
color col_ptm_1609, prot and resi 1609
set_color col_ptm_1813, [0.956, 0.956, 1.000]
show spheres, prot and resi 1813
color col_ptm_1813, prot and resi 1813
set_color col_ptm_2082, [1.000, 0.966, 0.966]
show spheres, prot and resi 2082
color col_ptm_2082, prot and resi 2082
set_color col_ptm_2155, [0.962, 0.962, 1.000]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_2203, [1.000, 0.999, 0.999]
show spheres, prot and resi 2203
color col_ptm_2203, prot and resi 2203
set_color col_ptm_2318, [1.000, 0.989, 0.989]
show spheres, prot and resi 2318
color col_ptm_2318, prot and resi 2318
set_color col_ptm_664, [0.942, 0.942, 1.000]
show spheres, prot and resi 664
color col_ptm_664, prot and resi 664
set_color col_ptm_768, [1.000, 0.980, 0.980]
show spheres, prot and resi 768
color col_ptm_768, prot and resi 768
set_color col_ptm_809, [0.969, 0.969, 1.000]
show spheres, prot and resi 809
color col_ptm_809, prot and resi 809
set_color col_ptm_1344, [0.931, 0.931, 1.000]
show spheres, prot and resi 1344
color col_ptm_1344, prot and resi 1344
set_color col_ptm_1492, [0.977, 0.977, 1.000]
show spheres, prot and resi 1492
color col_ptm_1492, prot and resi 1492
set_color col_ptm_2227, [1.000, 0.987, 0.987]
show spheres, prot and resi 2227
color col_ptm_2227, prot and resi 2227
set_color col_ptm_472, [1.000, 0.994, 0.994]
show spheres, prot and resi 472
color col_ptm_472, prot and resi 472
set_color col_ptm_1082, [1.000, 0.834, 0.834]
show spheres, prot and resi 1082
color col_ptm_1082, prot and resi 1082
set_color col_ptm_1345, [1.000, 0.921, 0.921]
show spheres, prot and resi 1345
color col_ptm_1345, prot and resi 1345
set_color col_ptm_1609, [0.898, 0.898, 1.000]
show spheres, prot and resi 1609
color col_ptm_1609, prot and resi 1609
set_color col_ptm_1813, [1.000, 0.983, 0.983]
show spheres, prot and resi 1813
color col_ptm_1813, prot and resi 1813
set_color col_ptm_2082, [0.975, 0.975, 1.000]
show spheres, prot and resi 2082
color col_ptm_2082, prot and resi 2082
set_color col_ptm_2155, [1.000, 0.999, 0.999]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_2203, [0.963, 0.963, 1.000]
show spheres, prot and resi 2203
color col_ptm_2203, prot and resi 2203
set_color col_ptm_2318, [0.961, 0.961, 1.000]
show spheres, prot and resi 2318
color col_ptm_2318, prot and resi 2318
set_color col_ptm_664, [1.000, 0.979, 0.979]
show spheres, prot and resi 664
color col_ptm_664, prot and resi 664
set_color col_ptm_768, [0.963, 0.963, 1.000]
show spheres, prot and resi 768
color col_ptm_768, prot and resi 768
set_color col_ptm_809, [1.000, 0.955, 0.955]
show spheres, prot and resi 809
color col_ptm_809, prot and resi 809
set_color col_ptm_1344, [0.926, 0.926, 1.000]
show spheres, prot and resi 1344
color col_ptm_1344, prot and resi 1344
set_color col_ptm_1492, [0.955, 0.955, 1.000]
show spheres, prot and resi 1492
color col_ptm_1492, prot and resi 1492
set_color col_ptm_2227, [1.000, 0.964, 0.964]
show spheres, prot and resi 2227
color col_ptm_2227, prot and resi 2227
set_color col_ptm_472, [1.000, 1.000, 1.000]
show spheres, prot and resi 472
color col_ptm_472, prot and resi 472
set_color col_ptm_1082, [1.000, 0.808, 0.808]
show spheres, prot and resi 1082
color col_ptm_1082, prot and resi 1082
set_color col_ptm_1345, [1.000, 0.943, 0.943]
show spheres, prot and resi 1345
color col_ptm_1345, prot and resi 1345
set_color col_ptm_1609, [0.972, 0.972, 1.000]
show spheres, prot and resi 1609
color col_ptm_1609, prot and resi 1609
set_color col_ptm_1813, [1.000, 0.973, 0.973]
show spheres, prot and resi 1813
color col_ptm_1813, prot and resi 1813
set_color col_ptm_2082, [0.901, 0.901, 1.000]
show spheres, prot and resi 2082
color col_ptm_2082, prot and resi 2082
set_color col_ptm_2155, [1.000, 0.987, 0.987]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_2203, [0.984, 0.984, 1.000]
show spheres, prot and resi 2203
color col_ptm_2203, prot and resi 2203
set_color col_ptm_2318, [0.948, 0.948, 1.000]
show spheres, prot and resi 2318
color col_ptm_2318, prot and resi 2318
set_color col_ptm_664, [0.928, 0.928, 1.000]
show spheres, prot and resi 664
color col_ptm_664, prot and resi 664
set_color col_ptm_768, [0.956, 0.956, 1.000]
show spheres, prot and resi 768
color col_ptm_768, prot and resi 768
set_color col_ptm_809, [1.000, 0.963, 0.963]
show spheres, prot and resi 809
color col_ptm_809, prot and resi 809
set_color col_ptm_1344, [0.606, 0.606, 1.000]
show spheres, prot and resi 1344
color col_ptm_1344, prot and resi 1344
set_color col_ptm_1492, [0.920, 0.920, 1.000]
show spheres, prot and resi 1492
color col_ptm_1492, prot and resi 1492
set_color col_ptm_2227, [1.000, 0.997, 0.997]
show spheres, prot and resi 2227
color col_ptm_2227, prot and resi 2227
set_color col_ptm_472, [1.000, 0.995, 0.995]
show spheres, prot and resi 472
color col_ptm_472, prot and resi 472
set_color col_ptm_1082, [1.000, 0.982, 0.982]
show spheres, prot and resi 1082
color col_ptm_1082, prot and resi 1082
set_color col_ptm_1345, [0.807, 0.807, 1.000]
show spheres, prot and resi 1345
color col_ptm_1345, prot and resi 1345
set_color col_ptm_1609, [0.861, 0.861, 1.000]
show spheres, prot and resi 1609
color col_ptm_1609, prot and resi 1609
set_color col_ptm_1813, [0.784, 0.784, 1.000]
show spheres, prot and resi 1813
color col_ptm_1813, prot and resi 1813
label prot and resi 1813 and name CA, "S1813 (log2FC=-0.43)"
set_color col_ptm_2082, [0.833, 0.833, 1.000]
show spheres, prot and resi 2082
color col_ptm_2082, prot and resi 2082
set_color col_ptm_2155, [0.869, 0.869, 1.000]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_2203, [0.885, 0.885, 1.000]
show spheres, prot and resi 2203
color col_ptm_2203, prot and resi 2203
set_color col_ptm_2318, [0.761, 0.761, 1.000]
show spheres, prot and resi 2318
color col_ptm_2318, prot and resi 2318
set_color col_ptm_664, [0.781, 0.781, 1.000]
show spheres, prot and resi 664
color col_ptm_664, prot and resi 664
set_color col_ptm_768, [0.782, 0.782, 1.000]
show spheres, prot and resi 768
color col_ptm_768, prot and resi 768
set_color col_ptm_809, [1.000, 0.991, 0.991]
show spheres, prot and resi 809
color col_ptm_809, prot and resi 809
set_color col_ptm_1344, [0.457, 0.457, 1.000]
show spheres, prot and resi 1344
color col_ptm_1344, prot and resi 1344
label prot and resi 1344 and name CA, "T1344 (log2FC=-1.09)"
set_color col_ptm_1492, [0.756, 0.756, 1.000]
show spheres, prot and resi 1492
color col_ptm_1492, prot and resi 1492
label prot and resi 1492 and name CA, "T1492 (log2FC=-0.49)"
set_color col_ptm_2227, [0.846, 0.846, 1.000]
show spheres, prot and resi 2227
color col_ptm_2227, prot and resi 2227
set_color col_ptm_472, [0.806, 0.806, 1.000]
show spheres, prot and resi 472
color col_ptm_472, prot and resi 472
set_color col_ptm_1082, [1.000, 0.489, 0.489]
show spheres, prot and resi 1082
color col_ptm_1082, prot and resi 1082
label prot and resi 1082 and name CA, "S1082 (log2FC=+1.02)"
set_color col_ptm_1345, [1.000, 0.649, 0.649]
show spheres, prot and resi 1345
color col_ptm_1345, prot and resi 1345
set_color col_ptm_1609, [1.000, 0.937, 0.937]
show spheres, prot and resi 1609
color col_ptm_1609, prot and resi 1609
set_color col_ptm_1813, [1.000, 0.839, 0.839]
show spheres, prot and resi 1813
color col_ptm_1813, prot and resi 1813
set_color col_ptm_2082, [0.979, 0.979, 1.000]
show spheres, prot and resi 2082
color col_ptm_2082, prot and resi 2082
set_color col_ptm_2155, [1.000, 0.937, 0.937]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_2203, [1.000, 0.940, 0.940]
show spheres, prot and resi 2203
color col_ptm_2203, prot and resi 2203
set_color col_ptm_2318, [0.769, 0.769, 1.000]
show spheres, prot and resi 2318
color col_ptm_2318, prot and resi 2318
set_color col_ptm_664, [1.000, 0.824, 0.824]
show spheres, prot and resi 664
color col_ptm_664, prot and resi 664
set_color col_ptm_768, [1.000, 0.913, 0.913]
show spheres, prot and resi 768
color col_ptm_768, prot and resi 768
set_color col_ptm_809, [1.000, 0.933, 0.933]
show spheres, prot and resi 809
color col_ptm_809, prot and resi 809
set_color col_ptm_1344, [0.590, 0.590, 1.000]
show spheres, prot and resi 1344
color col_ptm_1344, prot and resi 1344
label prot and resi 1344 and name CA, "T1344 (log2FC=-0.82)"
set_color col_ptm_1492, [1.000, 0.896, 0.896]
show spheres, prot and resi 1492
color col_ptm_1492, prot and resi 1492
set_color col_ptm_2227, [1.000, 0.868, 0.868]
show spheres, prot and resi 2227
color col_ptm_2227, prot and resi 2227
set_color col_ptm_472, [1.000, 0.872, 0.872]
show spheres, prot and resi 472
color col_ptm_472, prot and resi 472
set_color col_ptm_1082, [1.000, 0.886, 0.886]
show spheres, prot and resi 1082
color col_ptm_1082, prot and resi 1082
set_color col_ptm_1345, [1.000, 0.898, 0.898]
show spheres, prot and resi 1345
color col_ptm_1345, prot and resi 1345
set_color col_ptm_1609, [0.935, 0.935, 1.000]
show spheres, prot and resi 1609
color col_ptm_1609, prot and resi 1609
set_color col_ptm_1813, [1.000, 0.939, 0.939]
show spheres, prot and resi 1813
color col_ptm_1813, prot and resi 1813
set_color col_ptm_2082, [0.940, 0.940, 1.000]
show spheres, prot and resi 2082
color col_ptm_2082, prot and resi 2082
set_color col_ptm_2155, [1.000, 0.961, 0.961]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_2203, [0.961, 0.961, 1.000]
show spheres, prot and resi 2203
color col_ptm_2203, prot and resi 2203
set_color col_ptm_2318, [0.950, 0.950, 1.000]
show spheres, prot and resi 2318
color col_ptm_2318, prot and resi 2318
set_color col_ptm_664, [1.000, 0.921, 0.921]
show spheres, prot and resi 664
color col_ptm_664, prot and resi 664
set_color col_ptm_768, [0.943, 0.943, 1.000]
show spheres, prot and resi 768
color col_ptm_768, prot and resi 768
set_color col_ptm_809, [1.000, 0.924, 0.924]
show spheres, prot and resi 809
color col_ptm_809, prot and resi 809
set_color col_ptm_1344, [0.994, 0.994, 1.000]
show spheres, prot and resi 1344
color col_ptm_1344, prot and resi 1344
set_color col_ptm_1492, [0.978, 0.978, 1.000]
show spheres, prot and resi 1492
color col_ptm_1492, prot and resi 1492
set_color col_ptm_2227, [1.000, 0.977, 0.977]
show spheres, prot and resi 2227
color col_ptm_2227, prot and resi 2227
set_color col_ptm_472, [0.993, 0.993, 1.000]
show spheres, prot and resi 472
color col_ptm_472, prot and resi 472
set_color col_ptm_1082, [0.826, 0.826, 1.000]
show spheres, prot and resi 1082
color col_ptm_1082, prot and resi 1082
set_color col_ptm_1345, [0.750, 0.750, 1.000]
show spheres, prot and resi 1345
color col_ptm_1345, prot and resi 1345
set_color col_ptm_1609, [0.890, 0.890, 1.000]
show spheres, prot and resi 1609
color col_ptm_1609, prot and resi 1609
set_color col_ptm_1813, [0.757, 0.757, 1.000]
show spheres, prot and resi 1813
color col_ptm_1813, prot and resi 1813
set_color col_ptm_2082, [0.931, 0.931, 1.000]
show spheres, prot and resi 2082
color col_ptm_2082, prot and resi 2082
set_color col_ptm_2155, [0.855, 0.855, 1.000]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_2203, [0.900, 0.900, 1.000]
show spheres, prot and resi 2203
color col_ptm_2203, prot and resi 2203
set_color col_ptm_2318, [0.814, 0.814, 1.000]
show spheres, prot and resi 2318
color col_ptm_2318, prot and resi 2318
set_color col_ptm_664, [0.854, 0.854, 1.000]
show spheres, prot and resi 664
color col_ptm_664, prot and resi 664
set_color col_ptm_768, [0.826, 0.826, 1.000]
show spheres, prot and resi 768
color col_ptm_768, prot and resi 768
set_color col_ptm_809, [0.972, 0.972, 1.000]
show spheres, prot and resi 809
color col_ptm_809, prot and resi 809
set_color col_ptm_1344, [0.851, 0.851, 1.000]
show spheres, prot and resi 1344
color col_ptm_1344, prot and resi 1344
set_color col_ptm_1492, [0.836, 0.836, 1.000]
show spheres, prot and resi 1492
color col_ptm_1492, prot and resi 1492
set_color col_ptm_2227, [0.843, 0.843, 1.000]
show spheres, prot and resi 2227
color col_ptm_2227, prot and resi 2227
set_color col_ptm_472, [0.801, 0.801, 1.000]
show spheres, prot and resi 472
color col_ptm_472, prot and resi 472
set_color col_ptm_1082, [1.000, 0.777, 0.777]
show spheres, prot and resi 1082
color col_ptm_1082, prot and resi 1082
set_color col_ptm_1345, [0.999, 0.999, 1.000]
show spheres, prot and resi 1345
color col_ptm_1345, prot and resi 1345
set_color col_ptm_1609, [1.000, 0.983, 0.983]
show spheres, prot and resi 1609
color col_ptm_1609, prot and resi 1609
set_color col_ptm_1813, [0.857, 0.857, 1.000]
show spheres, prot and resi 1813
color col_ptm_1813, prot and resi 1813
set_color col_ptm_2082, [0.970, 0.970, 1.000]
show spheres, prot and resi 2082
color col_ptm_2082, prot and resi 2082
set_color col_ptm_2155, [0.879, 0.879, 1.000]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_2203, [0.999, 0.999, 1.000]
show spheres, prot and resi 2203
color col_ptm_2203, prot and resi 2203
set_color col_ptm_2318, [0.633, 0.633, 1.000]
show spheres, prot and resi 2318
color col_ptm_2318, prot and resi 2318
set_color col_ptm_664, [0.950, 0.950, 1.000]
show spheres, prot and resi 664
color col_ptm_664, prot and resi 664
set_color col_ptm_768, [0.970, 0.970, 1.000]
show spheres, prot and resi 768
color col_ptm_768, prot and resi 768
set_color col_ptm_809, [0.962, 0.962, 1.000]
show spheres, prot and resi 809
color col_ptm_809, prot and resi 809
set_color col_ptm_1344, [0.446, 0.446, 1.000]
show spheres, prot and resi 1344
color col_ptm_1344, prot and resi 1344
label prot and resi 1344 and name CA, "T1344 (log2FC=-1.11)"
set_color col_ptm_1492, [0.962, 0.962, 1.000]
show spheres, prot and resi 1492
color col_ptm_1492, prot and resi 1492
set_color col_ptm_2227, [0.952, 0.952, 1.000]
show spheres, prot and resi 2227
color col_ptm_2227, prot and resi 2227
set_color col_ptm_472, [0.935, 0.935, 1.000]
show spheres, prot and resi 472
color col_ptm_472, prot and resi 472
set_color col_ptm_1082, [0.808, 0.808, 1.000]
show spheres, prot and resi 1082
color col_ptm_1082, prot and resi 1082
set_color col_ptm_1345, [0.943, 0.943, 1.000]
show spheres, prot and resi 1345
color col_ptm_1345, prot and resi 1345
set_color col_ptm_1609, [1.000, 0.972, 0.972]
show spheres, prot and resi 1609
color col_ptm_1609, prot and resi 1609
set_color col_ptm_1813, [0.973, 0.973, 1.000]
show spheres, prot and resi 1813
color col_ptm_1813, prot and resi 1813
set_color col_ptm_2082, [1.000, 0.901, 0.901]
show spheres, prot and resi 2082
color col_ptm_2082, prot and resi 2082
set_color col_ptm_2155, [0.987, 0.987, 1.000]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_2203, [1.000, 0.984, 0.984]
show spheres, prot and resi 2203
color col_ptm_2203, prot and resi 2203
set_color col_ptm_2318, [1.000, 0.948, 0.948]
show spheres, prot and resi 2318
color col_ptm_2318, prot and resi 2318
set_color col_ptm_664, [1.000, 0.928, 0.928]
show spheres, prot and resi 664
color col_ptm_664, prot and resi 664
set_color col_ptm_768, [1.000, 0.956, 0.956]
show spheres, prot and resi 768
color col_ptm_768, prot and resi 768
set_color col_ptm_809, [0.963, 0.963, 1.000]
show spheres, prot and resi 809
color col_ptm_809, prot and resi 809
set_color col_ptm_1344, [1.000, 0.606, 0.606]
show spheres, prot and resi 1344
color col_ptm_1344, prot and resi 1344
set_color col_ptm_1492, [1.000, 0.920, 0.920]
show spheres, prot and resi 1492
color col_ptm_1492, prot and resi 1492
set_color col_ptm_2227, [0.997, 0.997, 1.000]
show spheres, prot and resi 2227
color col_ptm_2227, prot and resi 2227
set_color col_ptm_472, [0.995, 0.995, 1.000]
show spheres, prot and resi 472
color col_ptm_472, prot and resi 472
set_color col_ptm_1082, [1.000, 0.860, 0.860]
show spheres, prot and resi 1082
color col_ptm_1082, prot and resi 1082
set_color col_ptm_1345, [1.000, 0.920, 0.920]
show spheres, prot and resi 1345
color col_ptm_1345, prot and resi 1345
set_color col_ptm_1609, [1.000, 0.991, 0.991]
show spheres, prot and resi 1609
color col_ptm_1609, prot and resi 1609
set_color col_ptm_1813, [1.000, 0.929, 0.929]
show spheres, prot and resi 1813
color col_ptm_1813, prot and resi 1813
set_color col_ptm_2082, [0.867, 0.867, 1.000]
show spheres, prot and resi 2082
color col_ptm_2082, prot and resi 2082
set_color col_ptm_2155, [1.000, 0.949, 0.949]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_2203, [0.983, 0.983, 1.000]
show spheres, prot and resi 2203
color col_ptm_2203, prot and resi 2203
set_color col_ptm_2318, [0.936, 0.936, 1.000]
show spheres, prot and resi 2318
color col_ptm_2318, prot and resi 2318
set_color col_ptm_664, [0.985, 0.985, 1.000]
show spheres, prot and resi 664
color col_ptm_664, prot and resi 664
set_color col_ptm_768, [0.935, 0.935, 1.000]
show spheres, prot and resi 768
color col_ptm_768, prot and resi 768
set_color col_ptm_809, [1.000, 0.932, 0.932]
show spheres, prot and resi 809
color col_ptm_809, prot and resi 809
set_color col_ptm_1344, [0.675, 0.675, 1.000]
show spheres, prot and resi 1344
color col_ptm_1344, prot and resi 1344
set_color col_ptm_1492, [0.944, 0.944, 1.000]
show spheres, prot and resi 1492
color col_ptm_1492, prot and resi 1492
set_color col_ptm_2227, [0.991, 0.991, 1.000]
show spheres, prot and resi 2227
color col_ptm_2227, prot and resi 2227
set_color col_ptm_472, [0.999, 0.999, 1.000]
show spheres, prot and resi 472
color col_ptm_472, prot and resi 472
set_color col_ptm_1082, [0.631, 0.631, 1.000]
show spheres, prot and resi 1082
color col_ptm_1082, prot and resi 1082
label prot and resi 1082 and name CA, "S1082 (log2FC=-0.74)"
set_color col_ptm_1345, [0.793, 0.793, 1.000]
show spheres, prot and resi 1345
color col_ptm_1345, prot and resi 1345
label prot and resi 1345 and name CA, "S1345 (log2FC=-0.41)"
set_color col_ptm_1609, [0.956, 0.956, 1.000]
show spheres, prot and resi 1609
color col_ptm_1609, prot and resi 1609
set_color col_ptm_1813, [0.964, 0.964, 1.000]
show spheres, prot and resi 1813
color col_ptm_1813, prot and resi 1813
set_color col_ptm_2082, [0.980, 0.980, 1.000]
show spheres, prot and resi 2082
color col_ptm_2082, prot and resi 2082
set_color col_ptm_2155, [1.000, 0.984, 0.984]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_2203, [0.954, 0.954, 1.000]
show spheres, prot and resi 2203
color col_ptm_2203, prot and resi 2203
set_color col_ptm_2318, [1.000, 0.745, 0.745]
show spheres, prot and resi 2318
color col_ptm_2318, prot and resi 2318
set_color col_ptm_664, [0.895, 0.895, 1.000]
show spheres, prot and resi 664
color col_ptm_664, prot and resi 664
set_color col_ptm_768, [0.931, 0.931, 1.000]
show spheres, prot and resi 768
color col_ptm_768, prot and resi 768
set_color col_ptm_809, [0.991, 0.991, 1.000]
show spheres, prot and resi 809
color col_ptm_809, prot and resi 809
set_color col_ptm_1344, [1.000, 0.650, 0.650]
show spheres, prot and resi 1344
color col_ptm_1344, prot and resi 1344
label prot and resi 1344 and name CA, "T1344 (log2FC=+0.70)"
set_color col_ptm_1492, [0.925, 0.925, 1.000]
show spheres, prot and resi 1492
color col_ptm_1492, prot and resi 1492
set_color col_ptm_2227, [0.925, 0.925, 1.000]
show spheres, prot and resi 2227
color col_ptm_2227, prot and resi 2227
set_color col_ptm_472, [0.936, 0.936, 1.000]
show spheres, prot and resi 472
color col_ptm_472, prot and resi 472

set label_size, 16
set label_color, black
set label_font_id, 7
set sphere_scale, 0.8
orient prot
zoom prot, 5
ray 2000, 1500
# save output_3d/CIC_Q96RK0_pymol.png