# PyMOL Visualization Script for MAPK1 (Comparison)
# Generated by ptm3d Visualizer
reinitialize
bg_color white
load "/Users/jonasgrossmann/GitHub/PTMvisualizer/output_3d/structures/P28482.pdb", prot
hide everything, prot
show cartoon, prot
color gray80, prot

# Set up log2FC color spectrum
set b_factor_min, -2.0
set b_factor_max, 2.0

# Assign log2FC values to PTM residues
set_color col_ptm_185, [1.000, 0.812, 0.812]
show spheres, prot and resi 185
color col_ptm_185, prot and resi 185
set_color col_ptm_187, [1.000, 0.188, 0.188]
show spheres, prot and resi 187
color col_ptm_187, prot and resi 187
label prot and resi 187 and name CA, "Y187 (log2FC=+1.62)"
set_color col_ptm_185, [0.933, 0.933, 1.000]
show spheres, prot and resi 185
color col_ptm_185, prot and resi 185
set_color col_ptm_187, [1.000, 0.978, 0.978]
show spheres, prot and resi 187
color col_ptm_187, prot and resi 187
set_color col_ptm_185, [1.000, 0.990, 0.990]
show spheres, prot and resi 185
color col_ptm_185, prot and resi 185
set_color col_ptm_187, [1.000, 0.934, 0.934]
show spheres, prot and resi 187
color col_ptm_187, prot and resi 187
set_color col_ptm_185, [1.000, 0.714, 0.714]
show spheres, prot and resi 185
color col_ptm_185, prot and resi 185
set_color col_ptm_187, [1.000, 0.618, 0.618]
show spheres, prot and resi 187
color col_ptm_187, prot and resi 187
label prot and resi 187 and name CA, "Y187 (log2FC=+0.76)"
set_color col_ptm_185, [1.000, 0.713, 0.713]
show spheres, prot and resi 185
color col_ptm_185, prot and resi 185
label prot and resi 185 and name CA, "T185 (log2FC=+0.57)"
set_color col_ptm_187, [1.000, 0.622, 0.622]
show spheres, prot and resi 187
color col_ptm_187, prot and resi 187
label prot and resi 187 and name CA, "Y187 (log2FC=+0.76)"
set_color col_ptm_185, [1.000, 0.459, 0.459]
show spheres, prot and resi 185
color col_ptm_185, prot and resi 185
label prot and resi 185 and name CA, "T185 (log2FC=+1.08)"
set_color col_ptm_187, [1.000, 0.000, 0.000]
show spheres, prot and resi 187
color col_ptm_187, prot and resi 187
label prot and resi 187 and name CA, "Y187 (log2FC=+2.34)"
set_color col_ptm_185, [1.000, 0.923, 0.923]
show spheres, prot and resi 185
color col_ptm_185, prot and resi 185
set_color col_ptm_187, [1.000, 0.956, 0.956]
show spheres, prot and resi 187
color col_ptm_187, prot and resi 187
set_color col_ptm_185, [1.000, 0.999, 0.999]
show spheres, prot and resi 185
color col_ptm_185, prot and resi 185
set_color col_ptm_187, [0.997, 0.997, 1.000]
show spheres, prot and resi 187
color col_ptm_187, prot and resi 187
set_color col_ptm_185, [1.000, 0.535, 0.535]
show spheres, prot and resi 185
color col_ptm_185, prot and resi 185
label prot and resi 185 and name CA, "T185 (log2FC=+0.93)"
set_color col_ptm_187, [1.000, 0.000, 0.000]
show spheres, prot and resi 187
color col_ptm_187, prot and resi 187
label prot and resi 187 and name CA, "Y187 (log2FC=+2.25)"
set_color col_ptm_185, [0.714, 0.714, 1.000]
show spheres, prot and resi 185
color col_ptm_185, prot and resi 185
set_color col_ptm_187, [0.618, 0.618, 1.000]
show spheres, prot and resi 187
color col_ptm_187, prot and resi 187
label prot and resi 187 and name CA, "Y187 (log2FC=-0.76)"
set_color col_ptm_185, [1.000, 0.647, 0.647]
show spheres, prot and resi 185
color col_ptm_185, prot and resi 185
set_color col_ptm_187, [1.000, 0.641, 0.641]
show spheres, prot and resi 187
color col_ptm_187, prot and resi 187
set_color col_ptm_185, [0.602, 0.602, 1.000]
show spheres, prot and resi 185
color col_ptm_185, prot and resi 185
label prot and resi 185 and name CA, "T185 (log2FC=-0.80)"
set_color col_ptm_187, [0.000, 0.000, 1.000]
show spheres, prot and resi 187
color col_ptm_187, prot and resi 187
label prot and resi 187 and name CA, "Y187 (log2FC=-2.07)"

set label_size, 16
set label_color, black
set label_font_id, 7
set sphere_scale, 0.8
orient prot
zoom prot, 5
ray 2000, 1500
# save output_3d/MAPK1_P28482_pymol.png