# PyMOL Visualization Script for Q9UF83 (Comparison)
# Generated by ptm3d Visualizer
reinitialize
bg_color white
load "/Users/jonasgrossmann/GitHub/PTMvisualizer/output_3d/structures/Q9UF83.pdb", prot
hide everything, prot
show cartoon, prot
color gray80, prot

# Set up log2FC color spectrum
set b_factor_min, -2.0
set b_factor_max, 2.0

# Assign log2FC values to PTM residues
set_color col_ptm_100, [0.856, 0.856, 1.000]
show spheres, prot and resi 100
color col_ptm_100, prot and resi 100
set_color col_ptm_154, [0.832, 0.832, 1.000]
show spheres, prot and resi 154
color col_ptm_154, prot and resi 154
set_color col_ptm_177, [0.851, 0.851, 1.000]
show spheres, prot and resi 177
color col_ptm_177, prot and resi 177
set_color col_ptm_203, [0.765, 0.765, 1.000]
show spheres, prot and resi 203
color col_ptm_203, prot and resi 203
set_color col_ptm_238, [0.805, 0.805, 1.000]
show spheres, prot and resi 238
color col_ptm_238, prot and resi 238
set_color col_ptm_247, [0.742, 0.742, 1.000]
show spheres, prot and resi 247
color col_ptm_247, prot and resi 247
set_color col_ptm_251, [0.690, 0.690, 1.000]
show spheres, prot and resi 251
color col_ptm_251, prot and resi 251
set_color col_ptm_272, [0.730, 0.730, 1.000]
show spheres, prot and resi 272
color col_ptm_272, prot and resi 272
set_color col_ptm_317, [0.795, 0.795, 1.000]
show spheres, prot and resi 317
color col_ptm_317, prot and resi 317
set_color col_ptm_404, [0.776, 0.776, 1.000]
show spheres, prot and resi 404
color col_ptm_404, prot and resi 404
set_color col_ptm_413, [0.798, 0.798, 1.000]
show spheres, prot and resi 413
color col_ptm_413, prot and resi 413
set_color col_ptm_5, [0.762, 0.762, 1.000]
show spheres, prot and resi 5
color col_ptm_5, prot and resi 5
set_color col_ptm_519, [0.828, 0.828, 1.000]
show spheres, prot and resi 519
color col_ptm_519, prot and resi 519
set_color col_ptm_530, [0.794, 0.794, 1.000]
show spheres, prot and resi 530
color col_ptm_530, prot and resi 530
set_color col_ptm_539, [0.781, 0.781, 1.000]
show spheres, prot and resi 539
color col_ptm_539, prot and resi 539
set_color col_ptm_179, [0.851, 0.851, 1.000]
show spheres, prot and resi 179
color col_ptm_179, prot and resi 179
set_color col_ptm_196, [0.765, 0.765, 1.000]
show spheres, prot and resi 196
color col_ptm_196, prot and resi 196
set_color col_ptm_198, [0.765, 0.765, 1.000]
show spheres, prot and resi 198
color col_ptm_198, prot and resi 198
set_color col_ptm_249, [0.742, 0.742, 1.000]
show spheres, prot and resi 249
color col_ptm_249, prot and resi 249
set_color col_ptm_259, [0.820, 0.820, 1.000]
show spheres, prot and resi 259
color col_ptm_259, prot and resi 259
set_color col_ptm_267, [0.730, 0.730, 1.000]
show spheres, prot and resi 267
color col_ptm_267, prot and resi 267
set_color col_ptm_348, [0.765, 0.765, 1.000]
show spheres, prot and resi 348
color col_ptm_348, prot and resi 348
set_color col_ptm_357, [0.755, 0.755, 1.000]
show spheres, prot and resi 357
color col_ptm_357, prot and resi 357
set_color col_ptm_375, [0.891, 0.891, 1.000]
show spheres, prot and resi 375
color col_ptm_375, prot and resi 375
set_color col_ptm_483, [0.743, 0.743, 1.000]
show spheres, prot and resi 483
color col_ptm_483, prot and resi 483
set_color col_ptm_495, [0.801, 0.801, 1.000]
show spheres, prot and resi 495
color col_ptm_495, prot and resi 495
set_color col_ptm_510, [0.900, 0.900, 1.000]
show spheres, prot and resi 510
color col_ptm_510, prot and resi 510
set_color col_ptm_528, [0.802, 0.802, 1.000]
show spheres, prot and resi 528
color col_ptm_528, prot and resi 528
set_color col_ptm_65, [0.783, 0.783, 1.000]
show spheres, prot and resi 65
color col_ptm_65, prot and resi 65
set_color col_ptm_100, [0.925, 0.925, 1.000]
show spheres, prot and resi 100
color col_ptm_100, prot and resi 100
set_color col_ptm_154, [0.931, 0.931, 1.000]
show spheres, prot and resi 154
color col_ptm_154, prot and resi 154
set_color col_ptm_177, [0.962, 0.962, 1.000]
show spheres, prot and resi 177
color col_ptm_177, prot and resi 177
set_color col_ptm_203, [0.875, 0.875, 1.000]
show spheres, prot and resi 203
color col_ptm_203, prot and resi 203
set_color col_ptm_238, [1.000, 0.967, 0.967]
show spheres, prot and resi 238
color col_ptm_238, prot and resi 238
set_color col_ptm_247, [0.936, 0.936, 1.000]
show spheres, prot and resi 247
color col_ptm_247, prot and resi 247
set_color col_ptm_251, [0.983, 0.983, 1.000]
show spheres, prot and resi 251
color col_ptm_251, prot and resi 251
set_color col_ptm_272, [0.889, 0.889, 1.000]
show spheres, prot and resi 272
color col_ptm_272, prot and resi 272
set_color col_ptm_317, [0.938, 0.938, 1.000]
show spheres, prot and resi 317
color col_ptm_317, prot and resi 317
set_color col_ptm_404, [0.975, 0.975, 1.000]
show spheres, prot and resi 404
color col_ptm_404, prot and resi 404
set_color col_ptm_413, [0.908, 0.908, 1.000]
show spheres, prot and resi 413
color col_ptm_413, prot and resi 413
set_color col_ptm_5, [0.877, 0.877, 1.000]
show spheres, prot and resi 5
color col_ptm_5, prot and resi 5
set_color col_ptm_519, [0.951, 0.951, 1.000]
show spheres, prot and resi 519
color col_ptm_519, prot and resi 519
set_color col_ptm_530, [0.900, 0.900, 1.000]
show spheres, prot and resi 530
color col_ptm_530, prot and resi 530
set_color col_ptm_539, [0.816, 0.816, 1.000]
show spheres, prot and resi 539
color col_ptm_539, prot and resi 539
set_color col_ptm_179, [0.962, 0.962, 1.000]
show spheres, prot and resi 179
color col_ptm_179, prot and resi 179
set_color col_ptm_196, [0.875, 0.875, 1.000]
show spheres, prot and resi 196
color col_ptm_196, prot and resi 196
set_color col_ptm_198, [0.875, 0.875, 1.000]
show spheres, prot and resi 198
color col_ptm_198, prot and resi 198
set_color col_ptm_249, [0.936, 0.936, 1.000]
show spheres, prot and resi 249
color col_ptm_249, prot and resi 249
set_color col_ptm_259, [0.939, 0.939, 1.000]
show spheres, prot and resi 259
color col_ptm_259, prot and resi 259
set_color col_ptm_267, [0.889, 0.889, 1.000]
show spheres, prot and resi 267
color col_ptm_267, prot and resi 267
set_color col_ptm_348, [0.886, 0.886, 1.000]
show spheres, prot and resi 348
color col_ptm_348, prot and resi 348
set_color col_ptm_357, [0.872, 0.872, 1.000]
show spheres, prot and resi 357
color col_ptm_357, prot and resi 357
set_color col_ptm_375, [0.953, 0.953, 1.000]
show spheres, prot and resi 375
color col_ptm_375, prot and resi 375
set_color col_ptm_483, [0.885, 0.885, 1.000]
show spheres, prot and resi 483
color col_ptm_483, prot and resi 483
set_color col_ptm_495, [0.889, 0.889, 1.000]
show spheres, prot and resi 495
color col_ptm_495, prot and resi 495
set_color col_ptm_510, [0.893, 0.893, 1.000]
show spheres, prot and resi 510
color col_ptm_510, prot and resi 510
set_color col_ptm_528, [0.839, 0.839, 1.000]
show spheres, prot and resi 528
color col_ptm_528, prot and resi 528
set_color col_ptm_65, [0.836, 0.836, 1.000]
show spheres, prot and resi 65
color col_ptm_65, prot and resi 65
set_color col_ptm_100, [1.000, 0.980, 0.980]
show spheres, prot and resi 100
color col_ptm_100, prot and resi 100
set_color col_ptm_154, [0.914, 0.914, 1.000]
show spheres, prot and resi 154
color col_ptm_154, prot and resi 154
set_color col_ptm_177, [0.955, 0.955, 1.000]
show spheres, prot and resi 177
color col_ptm_177, prot and resi 177
set_color col_ptm_203, [0.869, 0.869, 1.000]
show spheres, prot and resi 203
color col_ptm_203, prot and resi 203
set_color col_ptm_238, [0.893, 0.893, 1.000]
show spheres, prot and resi 238
color col_ptm_238, prot and resi 238
set_color col_ptm_247, [0.901, 0.901, 1.000]
show spheres, prot and resi 247
color col_ptm_247, prot and resi 247
set_color col_ptm_251, [0.772, 0.772, 1.000]
show spheres, prot and resi 251
color col_ptm_251, prot and resi 251
set_color col_ptm_272, [0.881, 0.881, 1.000]
show spheres, prot and resi 272
color col_ptm_272, prot and resi 272
set_color col_ptm_317, [0.964, 0.964, 1.000]
show spheres, prot and resi 317
color col_ptm_317, prot and resi 317
set_color col_ptm_404, [0.971, 0.971, 1.000]
show spheres, prot and resi 404
color col_ptm_404, prot and resi 404
set_color col_ptm_413, [0.977, 0.977, 1.000]
show spheres, prot and resi 413
color col_ptm_413, prot and resi 413
set_color col_ptm_5, [0.918, 0.918, 1.000]
show spheres, prot and resi 5
color col_ptm_5, prot and resi 5
set_color col_ptm_519, [1.000, 0.987, 0.987]
show spheres, prot and resi 519
color col_ptm_519, prot and resi 519
set_color col_ptm_530, [0.997, 0.997, 1.000]
show spheres, prot and resi 530
color col_ptm_530, prot and resi 530
set_color col_ptm_539, [0.937, 0.937, 1.000]
show spheres, prot and resi 539
color col_ptm_539, prot and resi 539
set_color col_ptm_179, [0.955, 0.955, 1.000]
show spheres, prot and resi 179
color col_ptm_179, prot and resi 179
set_color col_ptm_196, [0.869, 0.869, 1.000]
show spheres, prot and resi 196
color col_ptm_196, prot and resi 196
set_color col_ptm_198, [0.869, 0.869, 1.000]
show spheres, prot and resi 198
color col_ptm_198, prot and resi 198
set_color col_ptm_249, [0.901, 0.901, 1.000]
show spheres, prot and resi 249
color col_ptm_249, prot and resi 249
set_color col_ptm_259, [0.947, 0.947, 1.000]
show spheres, prot and resi 259
color col_ptm_259, prot and resi 259
set_color col_ptm_267, [0.881, 0.881, 1.000]
show spheres, prot and resi 267
color col_ptm_267, prot and resi 267
set_color col_ptm_348, [0.919, 0.919, 1.000]
show spheres, prot and resi 348
color col_ptm_348, prot and resi 348
set_color col_ptm_357, [0.922, 0.922, 1.000]
show spheres, prot and resi 357
color col_ptm_357, prot and resi 357
set_color col_ptm_375, [1.000, 0.983, 0.983]
show spheres, prot and resi 375
color col_ptm_375, prot and resi 375
set_color col_ptm_483, [0.904, 0.904, 1.000]
show spheres, prot and resi 483
color col_ptm_483, prot and resi 483
set_color col_ptm_495, [0.928, 0.928, 1.000]
show spheres, prot and resi 495
color col_ptm_495, prot and resi 495
set_color col_ptm_510, [0.966, 0.966, 1.000]
show spheres, prot and resi 510
color col_ptm_510, prot and resi 510
set_color col_ptm_528, [0.964, 0.964, 1.000]
show spheres, prot and resi 528
color col_ptm_528, prot and resi 528
set_color col_ptm_65, [0.907, 0.907, 1.000]
show spheres, prot and resi 65
color col_ptm_65, prot and resi 65
set_color col_ptm_100, [1.000, 0.999, 0.999]
show spheres, prot and resi 100
color col_ptm_100, prot and resi 100
set_color col_ptm_154, [1.000, 0.947, 0.947]
show spheres, prot and resi 154
color col_ptm_154, prot and resi 154
set_color col_ptm_177, [1.000, 0.962, 0.962]
show spheres, prot and resi 177
color col_ptm_177, prot and resi 177
set_color col_ptm_203, [1.000, 0.911, 0.911]
show spheres, prot and resi 203
color col_ptm_203, prot and resi 203
set_color col_ptm_238, [1.000, 0.883, 0.883]
show spheres, prot and resi 238
color col_ptm_238, prot and resi 238
set_color col_ptm_247, [1.000, 0.852, 0.852]
show spheres, prot and resi 247
color col_ptm_247, prot and resi 247
set_color col_ptm_251, [0.633, 0.633, 1.000]
show spheres, prot and resi 251
color col_ptm_251, prot and resi 251
set_color col_ptm_272, [1.000, 0.907, 0.907]
show spheres, prot and resi 272
color col_ptm_272, prot and resi 272
set_color col_ptm_317, [1.000, 0.898, 0.898]
show spheres, prot and resi 317
color col_ptm_317, prot and resi 317
set_color col_ptm_404, [1.000, 0.862, 0.862]
show spheres, prot and resi 404
color col_ptm_404, prot and resi 404
set_color col_ptm_413, [1.000, 0.903, 0.903]
show spheres, prot and resi 413
color col_ptm_413, prot and resi 413
set_color col_ptm_5, [1.000, 0.914, 0.914]
show spheres, prot and resi 5
color col_ptm_5, prot and resi 5
set_color col_ptm_519, [1.000, 0.840, 0.840]
show spheres, prot and resi 519
color col_ptm_519, prot and resi 519
set_color col_ptm_530, [1.000, 0.858, 0.858]
show spheres, prot and resi 530
color col_ptm_530, prot and resi 530
set_color col_ptm_539, [1.000, 0.919, 0.919]
show spheres, prot and resi 539
color col_ptm_539, prot and resi 539
set_color col_ptm_179, [1.000, 0.962, 0.962]
show spheres, prot and resi 179
color col_ptm_179, prot and resi 179
set_color col_ptm_196, [1.000, 0.911, 0.911]
show spheres, prot and resi 196
color col_ptm_196, prot and resi 196
set_color col_ptm_198, [1.000, 0.911, 0.911]
show spheres, prot and resi 198
color col_ptm_198, prot and resi 198
set_color col_ptm_249, [1.000, 0.852, 0.852]
show spheres, prot and resi 249
color col_ptm_249, prot and resi 249
set_color col_ptm_259, [1.000, 0.869, 0.869]
show spheres, prot and resi 259
color col_ptm_259, prot and resi 259
set_color col_ptm_267, [1.000, 0.907, 0.907]
show spheres, prot and resi 267
color col_ptm_267, prot and resi 267
set_color col_ptm_348, [1.000, 0.891, 0.891]
show spheres, prot and resi 348
color col_ptm_348, prot and resi 348
set_color col_ptm_357, [1.000, 0.901, 0.901]
show spheres, prot and resi 357
color col_ptm_357, prot and resi 357
set_color col_ptm_375, [1.000, 0.930, 0.930]
show spheres, prot and resi 375
color col_ptm_375, prot and resi 375
set_color col_ptm_483, [1.000, 0.874, 0.874]
show spheres, prot and resi 483
color col_ptm_483, prot and resi 483
set_color col_ptm_495, [1.000, 0.867, 0.867]
show spheres, prot and resi 495
color col_ptm_495, prot and resi 495
set_color col_ptm_510, [1.000, 0.944, 0.944]
show spheres, prot and resi 510
color col_ptm_510, prot and resi 510
set_color col_ptm_528, [1.000, 0.918, 0.918]
show spheres, prot and resi 528
color col_ptm_528, prot and resi 528
set_color col_ptm_65, [0.996, 0.996, 1.000]
show spheres, prot and resi 65
color col_ptm_65, prot and resi 65
set_color col_ptm_100, [1.000, 0.850, 0.850]
show spheres, prot and resi 100
color col_ptm_100, prot and resi 100
set_color col_ptm_154, [1.000, 0.667, 0.667]
show spheres, prot and resi 154
color col_ptm_154, prot and resi 154
label prot and resi 154 and name CA, "S154 (log2FC=+0.67)"
set_color col_ptm_177, [1.000, 0.705, 0.705]
show spheres, prot and resi 177
color col_ptm_177, prot and resi 177
set_color col_ptm_203, [1.000, 0.591, 0.591]
show spheres, prot and resi 203
color col_ptm_203, prot and resi 203
label prot and resi 203 and name CA, "S203 (log2FC=+0.82)"
set_color col_ptm_238, [1.000, 0.758, 0.758]
show spheres, prot and resi 238
color col_ptm_238, prot and resi 238
set_color col_ptm_247, [1.000, 0.641, 0.641]
show spheres, prot and resi 247
color col_ptm_247, prot and resi 247
label prot and resi 247 and name CA, "S247 (log2FC=+0.72)"
set_color col_ptm_251, [0.564, 0.564, 1.000]
show spheres, prot and resi 251
color col_ptm_251, prot and resi 251
label prot and resi 251 and name CA, "S251 (log2FC=-0.87)"
set_color col_ptm_272, [1.000, 0.608, 0.608]
show spheres, prot and resi 272
color col_ptm_272, prot and resi 272
label prot and resi 272 and name CA, "S272 (log2FC=+0.78)"
set_color col_ptm_317, [1.000, 0.648, 0.648]
show spheres, prot and resi 317
color col_ptm_317, prot and resi 317
label prot and resi 317 and name CA, "S317 (log2FC=+0.70)"
set_color col_ptm_404, [1.000, 0.583, 0.583]
show spheres, prot and resi 404
color col_ptm_404, prot and resi 404
set_color col_ptm_413, [1.000, 0.665, 0.665]
show spheres, prot and resi 413
color col_ptm_413, prot and resi 413
set_color col_ptm_5, [1.000, 0.669, 0.669]
show spheres, prot and resi 5
color col_ptm_5, prot and resi 5
set_color col_ptm_519, [1.000, 0.599, 0.599]
show spheres, prot and resi 519
color col_ptm_519, prot and resi 519
label prot and resi 519 and name CA, "S519 (log2FC=+0.80)"
set_color col_ptm_530, [1.000, 0.545, 0.545]
show spheres, prot and resi 530
color col_ptm_530, prot and resi 530
label prot and resi 530 and name CA, "S530 (log2FC=+0.91)"
set_color col_ptm_539, [1.000, 0.693, 0.693]
show spheres, prot and resi 539
color col_ptm_539, prot and resi 539
set_color col_ptm_179, [1.000, 0.705, 0.705]
show spheres, prot and resi 179
color col_ptm_179, prot and resi 179
set_color col_ptm_196, [1.000, 0.591, 0.591]
show spheres, prot and resi 196
color col_ptm_196, prot and resi 196
label prot and resi 196 and name CA, "T196 (log2FC=+0.82)"
set_color col_ptm_198, [1.000, 0.591, 0.591]
show spheres, prot and resi 198
color col_ptm_198, prot and resi 198
label prot and resi 198 and name CA, "T198 (log2FC=+0.82)"
set_color col_ptm_249, [1.000, 0.641, 0.641]
show spheres, prot and resi 249
color col_ptm_249, prot and resi 249
label prot and resi 249 and name CA, "T249 (log2FC=+0.72)"
set_color col_ptm_259, [1.000, 0.672, 0.672]
show spheres, prot and resi 259
color col_ptm_259, prot and resi 259
set_color col_ptm_267, [1.000, 0.608, 0.608]
show spheres, prot and resi 267
color col_ptm_267, prot and resi 267
label prot and resi 267 and name CA, "T267 (log2FC=+0.78)"
set_color col_ptm_348, [1.000, 0.660, 0.660]
show spheres, prot and resi 348
color col_ptm_348, prot and resi 348
set_color col_ptm_357, [1.000, 0.695, 0.695]
show spheres, prot and resi 357
color col_ptm_357, prot and resi 357
set_color col_ptm_375, [1.000, 0.691, 0.691]
show spheres, prot and resi 375
color col_ptm_375, prot and resi 375
set_color col_ptm_483, [1.000, 0.704, 0.704]
show spheres, prot and resi 483
color col_ptm_483, prot and resi 483
set_color col_ptm_495, [1.000, 0.724, 0.724]
show spheres, prot and resi 495
color col_ptm_495, prot and resi 495
set_color col_ptm_510, [1.000, 0.720, 0.720]
show spheres, prot and resi 510
color col_ptm_510, prot and resi 510
set_color col_ptm_528, [1.000, 0.646, 0.646]
show spheres, prot and resi 528
color col_ptm_528, prot and resi 528
set_color col_ptm_65, [1.000, 0.645, 0.645]
show spheres, prot and resi 65
color col_ptm_65, prot and resi 65
set_color col_ptm_100, [0.932, 0.932, 1.000]
show spheres, prot and resi 100
color col_ptm_100, prot and resi 100
set_color col_ptm_154, [0.955, 0.955, 1.000]
show spheres, prot and resi 154
color col_ptm_154, prot and resi 154
set_color col_ptm_177, [0.928, 0.928, 1.000]
show spheres, prot and resi 177
color col_ptm_177, prot and resi 177
set_color col_ptm_203, [0.978, 0.978, 1.000]
show spheres, prot and resi 203
color col_ptm_203, prot and resi 203
set_color col_ptm_238, [0.889, 0.889, 1.000]
show spheres, prot and resi 238
color col_ptm_238, prot and resi 238
set_color col_ptm_247, [0.955, 0.955, 1.000]
show spheres, prot and resi 247
color col_ptm_247, prot and resi 247
set_color col_ptm_251, [0.340, 0.340, 1.000]
show spheres, prot and resi 251
color col_ptm_251, prot and resi 251
label prot and resi 251 and name CA, "S251 (log2FC=-1.32)"
set_color col_ptm_272, [0.934, 0.934, 1.000]
show spheres, prot and resi 272
color col_ptm_272, prot and resi 272
set_color col_ptm_317, [0.960, 0.960, 1.000]
show spheres, prot and resi 317
color col_ptm_317, prot and resi 317
set_color col_ptm_404, [0.939, 0.939, 1.000]
show spheres, prot and resi 404
color col_ptm_404, prot and resi 404
set_color col_ptm_413, [0.988, 0.988, 1.000]
show spheres, prot and resi 413
color col_ptm_413, prot and resi 413
set_color col_ptm_5, [0.970, 0.970, 1.000]
show spheres, prot and resi 5
color col_ptm_5, prot and resi 5
set_color col_ptm_519, [1.000, 0.963, 0.963]
show spheres, prot and resi 519
color col_ptm_519, prot and resi 519
set_color col_ptm_530, [1.000, 0.964, 0.964]
show spheres, prot and resi 530
color col_ptm_530, prot and resi 530
set_color col_ptm_539, [1.000, 0.954, 0.954]
show spheres, prot and resi 539
color col_ptm_539, prot and resi 539
set_color col_ptm_179, [0.928, 0.928, 1.000]
show spheres, prot and resi 179
color col_ptm_179, prot and resi 179
set_color col_ptm_196, [0.978, 0.978, 1.000]
show spheres, prot and resi 196
color col_ptm_196, prot and resi 196
set_color col_ptm_198, [0.978, 0.978, 1.000]
show spheres, prot and resi 198
color col_ptm_198, prot and resi 198
set_color col_ptm_249, [0.955, 0.955, 1.000]
show spheres, prot and resi 249
color col_ptm_249, prot and resi 249
set_color col_ptm_259, [1.000, 0.987, 0.987]
show spheres, prot and resi 259
color col_ptm_259, prot and resi 259
set_color col_ptm_267, [0.934, 0.934, 1.000]
show spheres, prot and resi 267
color col_ptm_267, prot and resi 267
set_color col_ptm_348, [0.988, 0.988, 1.000]
show spheres, prot and resi 348
color col_ptm_348, prot and resi 348
set_color col_ptm_357, [0.982, 0.982, 1.000]
show spheres, prot and resi 357
color col_ptm_357, prot and resi 357
set_color col_ptm_375, [1.000, 0.991, 0.991]
show spheres, prot and resi 375
color col_ptm_375, prot and resi 375
set_color col_ptm_483, [0.985, 0.985, 1.000]
show spheres, prot and resi 483
color col_ptm_483, prot and resi 483
set_color col_ptm_495, [1.000, 0.955, 0.955]
show spheres, prot and resi 495
color col_ptm_495, prot and resi 495
set_color col_ptm_510, [1.000, 0.937, 0.937]
show spheres, prot and resi 510
color col_ptm_510, prot and resi 510
set_color col_ptm_528, [1.000, 0.955, 0.955]
show spheres, prot and resi 528
color col_ptm_528, prot and resi 528
set_color col_ptm_65, [0.942, 0.942, 1.000]
show spheres, prot and resi 65
color col_ptm_65, prot and resi 65
set_color col_ptm_100, [1.000, 0.905, 0.905]
show spheres, prot and resi 100
color col_ptm_100, prot and resi 100
set_color col_ptm_154, [0.983, 0.983, 1.000]
show spheres, prot and resi 154
color col_ptm_154, prot and resi 154
set_color col_ptm_177, [0.994, 0.994, 1.000]
show spheres, prot and resi 177
color col_ptm_177, prot and resi 177
set_color col_ptm_203, [0.994, 0.994, 1.000]
show spheres, prot and resi 203
color col_ptm_203, prot and resi 203
set_color col_ptm_238, [0.860, 0.860, 1.000]
show spheres, prot and resi 238
color col_ptm_238, prot and resi 238
set_color col_ptm_247, [0.965, 0.965, 1.000]
show spheres, prot and resi 247
color col_ptm_247, prot and resi 247
set_color col_ptm_251, [0.789, 0.789, 1.000]
show spheres, prot and resi 251
color col_ptm_251, prot and resi 251
set_color col_ptm_272, [0.992, 0.992, 1.000]
show spheres, prot and resi 272
color col_ptm_272, prot and resi 272
set_color col_ptm_317, [1.000, 0.974, 0.974]
show spheres, prot and resi 317
color col_ptm_317, prot and resi 317
set_color col_ptm_404, [0.996, 0.996, 1.000]
show spheres, prot and resi 404
color col_ptm_404, prot and resi 404
set_color col_ptm_413, [1.000, 0.930, 0.930]
show spheres, prot and resi 413
color col_ptm_413, prot and resi 413
set_color col_ptm_5, [1.000, 0.960, 0.960]
show spheres, prot and resi 5
color col_ptm_5, prot and resi 5
set_color col_ptm_519, [1.000, 0.938, 0.938]
show spheres, prot and resi 519
color col_ptm_519, prot and resi 519
set_color col_ptm_530, [1.000, 0.903, 0.903]
show spheres, prot and resi 530
color col_ptm_530, prot and resi 530
set_color col_ptm_539, [1.000, 0.879, 0.879]
show spheres, prot and resi 539
color col_ptm_539, prot and resi 539
set_color col_ptm_179, [0.994, 0.994, 1.000]
show spheres, prot and resi 179
color col_ptm_179, prot and resi 179
set_color col_ptm_196, [0.994, 0.994, 1.000]
show spheres, prot and resi 196
color col_ptm_196, prot and resi 196
set_color col_ptm_198, [0.994, 0.994, 1.000]
show spheres, prot and resi 198
color col_ptm_198, prot and resi 198
set_color col_ptm_249, [0.965, 0.965, 1.000]
show spheres, prot and resi 249
color col_ptm_249, prot and resi 249
set_color col_ptm_259, [1.000, 0.992, 0.992]
show spheres, prot and resi 259
color col_ptm_259, prot and resi 259
set_color col_ptm_267, [0.992, 0.992, 1.000]
show spheres, prot and resi 267
color col_ptm_267, prot and resi 267
set_color col_ptm_348, [1.000, 0.967, 0.967]
show spheres, prot and resi 348
color col_ptm_348, prot and resi 348
set_color col_ptm_357, [1.000, 0.950, 0.950]
show spheres, prot and resi 357
color col_ptm_357, prot and resi 357
set_color col_ptm_375, [1.000, 0.935, 0.935]
show spheres, prot and resi 375
color col_ptm_375, prot and resi 375
set_color col_ptm_483, [1.000, 0.981, 0.981]
show spheres, prot and resi 483
color col_ptm_483, prot and resi 483
set_color col_ptm_495, [1.000, 0.962, 0.962]
show spheres, prot and resi 495
color col_ptm_495, prot and resi 495
set_color col_ptm_510, [1.000, 0.927, 0.927]
show spheres, prot and resi 510
color col_ptm_510, prot and resi 510
set_color col_ptm_528, [1.000, 0.875, 0.875]
show spheres, prot and resi 528
color col_ptm_528, prot and resi 528
set_color col_ptm_65, [1.000, 0.929, 0.929]
show spheres, prot and resi 65
color col_ptm_65, prot and resi 65
set_color col_ptm_100, [1.000, 0.851, 0.851]
show spheres, prot and resi 100
color col_ptm_100, prot and resi 100
set_color col_ptm_154, [1.000, 0.721, 0.721]
show spheres, prot and resi 154
color col_ptm_154, prot and resi 154
set_color col_ptm_177, [1.000, 0.743, 0.743]
show spheres, prot and resi 177
color col_ptm_177, prot and resi 177
set_color col_ptm_203, [1.000, 0.680, 0.680]
show spheres, prot and resi 203
color col_ptm_203, prot and resi 203
set_color col_ptm_238, [1.000, 0.875, 0.875]
show spheres, prot and resi 238
color col_ptm_238, prot and resi 238
set_color col_ptm_247, [1.000, 0.789, 0.789]
show spheres, prot and resi 247
color col_ptm_247, prot and resi 247
set_color col_ptm_251, [0.932, 0.932, 1.000]
show spheres, prot and resi 251
color col_ptm_251, prot and resi 251
set_color col_ptm_272, [1.000, 0.701, 0.701]
show spheres, prot and resi 272
color col_ptm_272, prot and resi 272
set_color col_ptm_317, [1.000, 0.751, 0.751]
show spheres, prot and resi 317
color col_ptm_317, prot and resi 317
set_color col_ptm_404, [1.000, 0.721, 0.721]
show spheres, prot and resi 404
color col_ptm_404, prot and resi 404
set_color col_ptm_413, [1.000, 0.762, 0.762]
show spheres, prot and resi 413
color col_ptm_413, prot and resi 413
set_color col_ptm_5, [1.000, 0.754, 0.754]
show spheres, prot and resi 5
color col_ptm_5, prot and resi 5
set_color col_ptm_519, [1.000, 0.759, 0.759]
show spheres, prot and resi 519
color col_ptm_519, prot and resi 519
set_color col_ptm_530, [1.000, 0.687, 0.687]
show spheres, prot and resi 530
color col_ptm_530, prot and resi 530
set_color col_ptm_539, [1.000, 0.774, 0.774]
show spheres, prot and resi 539
color col_ptm_539, prot and resi 539
set_color col_ptm_179, [1.000, 0.743, 0.743]
show spheres, prot and resi 179
color col_ptm_179, prot and resi 179
set_color col_ptm_196, [1.000, 0.680, 0.680]
show spheres, prot and resi 196
color col_ptm_196, prot and resi 196
set_color col_ptm_198, [1.000, 0.680, 0.680]
show spheres, prot and resi 198
color col_ptm_198, prot and resi 198
set_color col_ptm_249, [1.000, 0.789, 0.789]
show spheres, prot and resi 249
color col_ptm_249, prot and resi 249
set_color col_ptm_259, [1.000, 0.803, 0.803]
show spheres, prot and resi 259
color col_ptm_259, prot and resi 259
set_color col_ptm_267, [1.000, 0.701, 0.701]
show spheres, prot and resi 267
color col_ptm_267, prot and resi 267
set_color col_ptm_348, [1.000, 0.769, 0.769]
show spheres, prot and resi 348
color col_ptm_348, prot and resi 348
set_color col_ptm_357, [1.000, 0.794, 0.794]
show spheres, prot and resi 357
color col_ptm_357, prot and resi 357
set_color col_ptm_375, [1.000, 0.761, 0.761]
show spheres, prot and resi 375
color col_ptm_375, prot and resi 375
set_color col_ptm_483, [1.000, 0.831, 0.831]
show spheres, prot and resi 483
color col_ptm_483, prot and resi 483
set_color col_ptm_495, [1.000, 0.857, 0.857]
show spheres, prot and resi 495
color col_ptm_495, prot and resi 495
set_color col_ptm_510, [1.000, 0.776, 0.776]
show spheres, prot and resi 510
color col_ptm_510, prot and resi 510
set_color col_ptm_528, [1.000, 0.728, 0.728]
show spheres, prot and resi 528
color col_ptm_528, prot and resi 528
set_color col_ptm_65, [1.000, 0.641, 0.641]
show spheres, prot and resi 65
color col_ptm_65, prot and resi 65
set_color col_ptm_100, [0.986, 0.986, 1.000]
show spheres, prot and resi 100
color col_ptm_100, prot and resi 100
set_color col_ptm_154, [1.000, 0.750, 0.750]
show spheres, prot and resi 154
color col_ptm_154, prot and resi 154
set_color col_ptm_177, [1.000, 0.809, 0.809]
show spheres, prot and resi 177
color col_ptm_177, prot and resi 177
set_color col_ptm_203, [1.000, 0.695, 0.695]
show spheres, prot and resi 203
color col_ptm_203, prot and resi 203
set_color col_ptm_238, [1.000, 0.846, 0.846]
show spheres, prot and resi 238
color col_ptm_238, prot and resi 238
set_color col_ptm_247, [1.000, 0.800, 0.800]
show spheres, prot and resi 247
color col_ptm_247, prot and resi 247
set_color col_ptm_251, [0.483, 0.483, 1.000]
show spheres, prot and resi 251
color col_ptm_251, prot and resi 251
set_color col_ptm_272, [1.000, 0.759, 0.759]
show spheres, prot and resi 272
color col_ptm_272, prot and resi 272
set_color col_ptm_317, [1.000, 0.817, 0.817]
show spheres, prot and resi 317
color col_ptm_317, prot and resi 317
set_color col_ptm_404, [1.000, 0.778, 0.778]
show spheres, prot and resi 404
color col_ptm_404, prot and resi 404
set_color col_ptm_413, [1.000, 0.844, 0.844]
show spheres, prot and resi 413
color col_ptm_413, prot and resi 413
set_color col_ptm_5, [1.000, 0.824, 0.824]
show spheres, prot and resi 5
color col_ptm_5, prot and resi 5
set_color col_ptm_519, [1.000, 0.785, 0.785]
show spheres, prot and resi 519
color col_ptm_519, prot and resi 519
set_color col_ptm_530, [1.000, 0.749, 0.749]
show spheres, prot and resi 530
color col_ptm_530, prot and resi 530
set_color col_ptm_539, [1.000, 0.849, 0.849]
show spheres, prot and resi 539
color col_ptm_539, prot and resi 539
set_color col_ptm_179, [1.000, 0.809, 0.809]
show spheres, prot and resi 179
color col_ptm_179, prot and resi 179
set_color col_ptm_196, [1.000, 0.695, 0.695]
show spheres, prot and resi 196
color col_ptm_196, prot and resi 196
set_color col_ptm_198, [1.000, 0.695, 0.695]
show spheres, prot and resi 198
color col_ptm_198, prot and resi 198
set_color col_ptm_249, [1.000, 0.800, 0.800]
show spheres, prot and resi 249
color col_ptm_249, prot and resi 249
set_color col_ptm_259, [1.000, 0.799, 0.799]
show spheres, prot and resi 259
color col_ptm_259, prot and resi 259
set_color col_ptm_267, [1.000, 0.759, 0.759]
show spheres, prot and resi 267
color col_ptm_267, prot and resi 267
set_color col_ptm_348, [1.000, 0.814, 0.814]
show spheres, prot and resi 348
color col_ptm_348, prot and resi 348
set_color col_ptm_357, [1.000, 0.862, 0.862]
show spheres, prot and resi 357
color col_ptm_357, prot and resi 357
set_color col_ptm_375, [1.000, 0.817, 0.817]
show spheres, prot and resi 375
color col_ptm_375, prot and resi 375
set_color col_ptm_483, [1.000, 0.865, 0.865]
show spheres, prot and resi 483
color col_ptm_483, prot and resi 483
set_color col_ptm_495, [1.000, 0.851, 0.851]
show spheres, prot and resi 495
color col_ptm_495, prot and resi 495
set_color col_ptm_510, [1.000, 0.786, 0.786]
show spheres, prot and resi 510
color col_ptm_510, prot and resi 510
set_color col_ptm_528, [1.000, 0.808, 0.808]
show spheres, prot and resi 528
color col_ptm_528, prot and resi 528
set_color col_ptm_65, [1.000, 0.770, 0.770]
show spheres, prot and resi 65
color col_ptm_65, prot and resi 65
set_color col_ptm_100, [0.999, 0.999, 1.000]
show spheres, prot and resi 100
color col_ptm_100, prot and resi 100
set_color col_ptm_154, [0.947, 0.947, 1.000]
show spheres, prot and resi 154
color col_ptm_154, prot and resi 154
set_color col_ptm_177, [0.962, 0.962, 1.000]
show spheres, prot and resi 177
color col_ptm_177, prot and resi 177
set_color col_ptm_203, [0.911, 0.911, 1.000]
show spheres, prot and resi 203
color col_ptm_203, prot and resi 203
set_color col_ptm_238, [0.883, 0.883, 1.000]
show spheres, prot and resi 238
color col_ptm_238, prot and resi 238
set_color col_ptm_247, [0.852, 0.852, 1.000]
show spheres, prot and resi 247
color col_ptm_247, prot and resi 247
set_color col_ptm_251, [1.000, 0.633, 0.633]
show spheres, prot and resi 251
color col_ptm_251, prot and resi 251
set_color col_ptm_272, [0.907, 0.907, 1.000]
show spheres, prot and resi 272
color col_ptm_272, prot and resi 272
set_color col_ptm_317, [0.898, 0.898, 1.000]
show spheres, prot and resi 317
color col_ptm_317, prot and resi 317
set_color col_ptm_404, [0.862, 0.862, 1.000]
show spheres, prot and resi 404
color col_ptm_404, prot and resi 404
set_color col_ptm_413, [0.903, 0.903, 1.000]
show spheres, prot and resi 413
color col_ptm_413, prot and resi 413
set_color col_ptm_5, [0.914, 0.914, 1.000]
show spheres, prot and resi 5
color col_ptm_5, prot and resi 5
set_color col_ptm_519, [0.840, 0.840, 1.000]
show spheres, prot and resi 519
color col_ptm_519, prot and resi 519
set_color col_ptm_530, [0.858, 0.858, 1.000]
show spheres, prot and resi 530
color col_ptm_530, prot and resi 530
set_color col_ptm_539, [0.919, 0.919, 1.000]
show spheres, prot and resi 539
color col_ptm_539, prot and resi 539
set_color col_ptm_179, [0.962, 0.962, 1.000]
show spheres, prot and resi 179
color col_ptm_179, prot and resi 179
set_color col_ptm_196, [0.911, 0.911, 1.000]
show spheres, prot and resi 196
color col_ptm_196, prot and resi 196
set_color col_ptm_198, [0.911, 0.911, 1.000]
show spheres, prot and resi 198
color col_ptm_198, prot and resi 198
set_color col_ptm_249, [0.852, 0.852, 1.000]
show spheres, prot and resi 249
color col_ptm_249, prot and resi 249
set_color col_ptm_259, [0.869, 0.869, 1.000]
show spheres, prot and resi 259
color col_ptm_259, prot and resi 259
set_color col_ptm_267, [0.907, 0.907, 1.000]
show spheres, prot and resi 267
color col_ptm_267, prot and resi 267
set_color col_ptm_348, [0.891, 0.891, 1.000]
show spheres, prot and resi 348
color col_ptm_348, prot and resi 348
set_color col_ptm_357, [0.901, 0.901, 1.000]
show spheres, prot and resi 357
color col_ptm_357, prot and resi 357
set_color col_ptm_375, [0.930, 0.930, 1.000]
show spheres, prot and resi 375
color col_ptm_375, prot and resi 375
set_color col_ptm_483, [0.874, 0.874, 1.000]
show spheres, prot and resi 483
color col_ptm_483, prot and resi 483
set_color col_ptm_495, [0.867, 0.867, 1.000]
show spheres, prot and resi 495
color col_ptm_495, prot and resi 495
set_color col_ptm_510, [0.944, 0.944, 1.000]
show spheres, prot and resi 510
color col_ptm_510, prot and resi 510
set_color col_ptm_528, [0.918, 0.918, 1.000]
show spheres, prot and resi 528
color col_ptm_528, prot and resi 528
set_color col_ptm_65, [1.000, 0.996, 0.996]
show spheres, prot and resi 65
color col_ptm_65, prot and resi 65
set_color col_ptm_100, [1.000, 0.924, 0.924]
show spheres, prot and resi 100
color col_ptm_100, prot and resi 100
set_color col_ptm_154, [1.000, 0.877, 0.877]
show spheres, prot and resi 154
color col_ptm_154, prot and resi 154
set_color col_ptm_177, [1.000, 0.924, 0.924]
show spheres, prot and resi 177
color col_ptm_177, prot and resi 177
set_color col_ptm_203, [1.000, 0.787, 0.787]
show spheres, prot and resi 203
color col_ptm_203, prot and resi 203
set_color col_ptm_238, [1.000, 0.916, 0.916]
show spheres, prot and resi 238
color col_ptm_238, prot and resi 238
set_color col_ptm_247, [1.000, 0.787, 0.787]
show spheres, prot and resi 247
color col_ptm_247, prot and resi 247
set_color col_ptm_251, [0.649, 0.649, 1.000]
show spheres, prot and resi 251
color col_ptm_251, prot and resi 251
set_color col_ptm_272, [1.000, 0.796, 0.796]
show spheres, prot and resi 272
color col_ptm_272, prot and resi 272
set_color col_ptm_317, [1.000, 0.836, 0.836]
show spheres, prot and resi 317
color col_ptm_317, prot and resi 317
set_color col_ptm_404, [1.000, 0.837, 0.837]
show spheres, prot and resi 404
color col_ptm_404, prot and resi 404
set_color col_ptm_413, [1.000, 0.811, 0.811]
show spheres, prot and resi 413
color col_ptm_413, prot and resi 413
set_color col_ptm_5, [1.000, 0.791, 0.791]
show spheres, prot and resi 5
color col_ptm_5, prot and resi 5
set_color col_ptm_519, [1.000, 0.791, 0.791]
show spheres, prot and resi 519
color col_ptm_519, prot and resi 519
set_color col_ptm_530, [1.000, 0.758, 0.758]
show spheres, prot and resi 530
color col_ptm_530, prot and resi 530
set_color col_ptm_539, [1.000, 0.735, 0.735]
show spheres, prot and resi 539
color col_ptm_539, prot and resi 539
set_color col_ptm_179, [1.000, 0.924, 0.924]
show spheres, prot and resi 179
color col_ptm_179, prot and resi 179
set_color col_ptm_196, [1.000, 0.787, 0.787]
show spheres, prot and resi 196
color col_ptm_196, prot and resi 196
set_color col_ptm_198, [1.000, 0.787, 0.787]
show spheres, prot and resi 198
color col_ptm_198, prot and resi 198
set_color col_ptm_249, [1.000, 0.787, 0.787]
show spheres, prot and resi 249
color col_ptm_249, prot and resi 249
set_color col_ptm_259, [1.000, 0.808, 0.808]
show spheres, prot and resi 259
color col_ptm_259, prot and resi 259
set_color col_ptm_267, [1.000, 0.796, 0.796]
show spheres, prot and resi 267
color col_ptm_267, prot and resi 267
set_color col_ptm_348, [1.000, 0.776, 0.776]
show spheres, prot and resi 348
color col_ptm_348, prot and resi 348
set_color col_ptm_357, [1.000, 0.773, 0.773]
show spheres, prot and resi 357
color col_ptm_357, prot and resi 357
set_color col_ptm_375, [1.000, 0.882, 0.882]
show spheres, prot and resi 375
color col_ptm_375, prot and resi 375
set_color col_ptm_483, [1.000, 0.758, 0.758]
show spheres, prot and resi 483
color col_ptm_483, prot and resi 483
set_color col_ptm_495, [1.000, 0.756, 0.756]
show spheres, prot and resi 495
color col_ptm_495, prot and resi 495
set_color col_ptm_510, [1.000, 0.837, 0.837]
show spheres, prot and resi 510
color col_ptm_510, prot and resi 510
set_color col_ptm_528, [1.000, 0.757, 0.757]
show spheres, prot and resi 528
color col_ptm_528, prot and resi 528
set_color col_ptm_65, [1.000, 0.840, 0.840]
show spheres, prot and resi 65
color col_ptm_65, prot and resi 65
set_color col_ptm_100, [1.000, 0.925, 0.925]
show spheres, prot and resi 100
color col_ptm_100, prot and resi 100
set_color col_ptm_154, [0.988, 0.988, 1.000]
show spheres, prot and resi 154
color col_ptm_154, prot and resi 154
set_color col_ptm_177, [1.000, 0.990, 0.990]
show spheres, prot and resi 177
color col_ptm_177, prot and resi 177
set_color col_ptm_203, [0.984, 0.984, 1.000]
show spheres, prot and resi 203
color col_ptm_203, prot and resi 203
set_color col_ptm_238, [1.000, 0.950, 0.950]
show spheres, prot and resi 238
color col_ptm_238, prot and resi 238
set_color col_ptm_247, [1.000, 0.966, 0.966]
show spheres, prot and resi 247
color col_ptm_247, prot and resi 247
set_color col_ptm_251, [1.000, 0.504, 0.504]
show spheres, prot and resi 251
color col_ptm_251, prot and resi 251
label prot and resi 251 and name CA, "S251 (log2FC=+0.99)"
set_color col_ptm_272, [1.000, 0.968, 0.968]
show spheres, prot and resi 272
color col_ptm_272, prot and resi 272
set_color col_ptm_317, [1.000, 0.979, 0.979]
show spheres, prot and resi 317
color col_ptm_317, prot and resi 317
set_color col_ptm_404, [1.000, 0.979, 0.979]
show spheres, prot and resi 404
color col_ptm_404, prot and resi 404
set_color col_ptm_413, [1.000, 0.981, 0.981]
show spheres, prot and resi 413
color col_ptm_413, prot and resi 413
set_color col_ptm_5, [1.000, 0.969, 0.969]
show spheres, prot and resi 5
color col_ptm_5, prot and resi 5
set_color col_ptm_519, [0.973, 0.973, 1.000]
show spheres, prot and resi 519
color col_ptm_519, prot and resi 519
set_color col_ptm_530, [0.973, 0.973, 1.000]
show spheres, prot and resi 530
color col_ptm_530, prot and resi 530
set_color col_ptm_539, [1.000, 0.992, 0.992]
show spheres, prot and resi 539
color col_ptm_539, prot and resi 539
set_color col_ptm_179, [1.000, 0.990, 0.990]
show spheres, prot and resi 179
color col_ptm_179, prot and resi 179
set_color col_ptm_196, [0.984, 0.984, 1.000]
show spheres, prot and resi 196
color col_ptm_196, prot and resi 196
set_color col_ptm_198, [0.984, 0.984, 1.000]
show spheres, prot and resi 198
color col_ptm_198, prot and resi 198
set_color col_ptm_249, [1.000, 0.966, 0.966]
show spheres, prot and resi 249
color col_ptm_249, prot and resi 249
set_color col_ptm_259, [0.989, 0.989, 1.000]
show spheres, prot and resi 259
color col_ptm_259, prot and resi 259
set_color col_ptm_267, [1.000, 0.968, 0.968]
show spheres, prot and resi 267
color col_ptm_267, prot and resi 267
set_color col_ptm_348, [1.000, 0.980, 0.980]
show spheres, prot and resi 348
color col_ptm_348, prot and resi 348
set_color col_ptm_357, [1.000, 0.958, 0.958]
show spheres, prot and resi 357
color col_ptm_357, prot and resi 357
set_color col_ptm_375, [0.973, 0.973, 1.000]
show spheres, prot and resi 375
color col_ptm_375, prot and resi 375
set_color col_ptm_483, [1.000, 0.954, 0.954]
show spheres, prot and resi 483
color col_ptm_483, prot and resi 483
set_color col_ptm_495, [1.000, 0.998, 0.998]
show spheres, prot and resi 495
color col_ptm_495, prot and resi 495
set_color col_ptm_510, [0.941, 0.941, 1.000]
show spheres, prot and resi 510
color col_ptm_510, prot and resi 510
set_color col_ptm_528, [0.987, 0.987, 1.000]
show spheres, prot and resi 528
color col_ptm_528, prot and resi 528
set_color col_ptm_65, [1.000, 0.985, 0.985]
show spheres, prot and resi 65
color col_ptm_65, prot and resi 65

set label_size, 16
set label_color, black
set label_font_id, 7
set sphere_scale, 0.8
orient prot
zoom prot, 5
ray 2000, 1500
# save output_3d/Q9UF83_Q9UF83_pymol.png