# PyMOL Visualization Script for TBC1D4 (Comparison)
# Generated by ptm3d Visualizer
reinitialize
bg_color white
load "/Users/jonasgrossmann/GitHub/PTMvisualizer/output_3d/structures/O60343.pdb", prot
hide everything, prot
show cartoon, prot
color gray80, prot

# Set up log2FC color spectrum
set b_factor_min, -2.0
set b_factor_max, 2.0

# Assign log2FC values to PTM residues
set_color col_ptm_341, [0.961, 0.961, 1.000]
show spheres, prot and resi 341
color col_ptm_341, prot and resi 341
set_color col_ptm_344, [0.973, 0.973, 1.000]
show spheres, prot and resi 344
color col_ptm_344, prot and resi 344
set_color col_ptm_588, [1.000, 0.090, 0.090]
show spheres, prot and resi 588
color col_ptm_588, prot and resi 588
label prot and resi 588 and name CA, "S588 (log2FC=+1.82)"
set_color col_ptm_591, [0.717, 0.717, 1.000]
show spheres, prot and resi 591
color col_ptm_591, prot and resi 591
set_color col_ptm_666, [1.000, 0.750, 0.750]
show spheres, prot and resi 666
color col_ptm_666, prot and resi 666
set_color col_ptm_642, [1.000, 0.575, 0.575]
show spheres, prot and resi 642
color col_ptm_642, prot and resi 642
set_color col_ptm_341, [1.000, 0.945, 0.945]
show spheres, prot and resi 341
color col_ptm_341, prot and resi 341
set_color col_ptm_344, [0.982, 0.982, 1.000]
show spheres, prot and resi 344
color col_ptm_344, prot and resi 344
set_color col_ptm_588, [0.970, 0.970, 1.000]
show spheres, prot and resi 588
color col_ptm_588, prot and resi 588
set_color col_ptm_591, [1.000, 0.928, 0.928]
show spheres, prot and resi 591
color col_ptm_591, prot and resi 591
set_color col_ptm_666, [0.907, 0.907, 1.000]
show spheres, prot and resi 666
color col_ptm_666, prot and resi 666
set_color col_ptm_642, [0.978, 0.978, 1.000]
show spheres, prot and resi 642
color col_ptm_642, prot and resi 642
set_color col_ptm_341, [1.000, 0.958, 0.958]
show spheres, prot and resi 341
color col_ptm_341, prot and resi 341
set_color col_ptm_344, [0.989, 0.989, 1.000]
show spheres, prot and resi 344
color col_ptm_344, prot and resi 344
set_color col_ptm_588, [1.000, 0.993, 0.993]
show spheres, prot and resi 588
color col_ptm_588, prot and resi 588
set_color col_ptm_591, [0.892, 0.892, 1.000]
show spheres, prot and resi 591
color col_ptm_591, prot and resi 591
set_color col_ptm_666, [0.998, 0.998, 1.000]
show spheres, prot and resi 666
color col_ptm_666, prot and resi 666
set_color col_ptm_642, [0.993, 0.993, 1.000]
show spheres, prot and resi 642
color col_ptm_642, prot and resi 642
set_color col_ptm_341, [1.000, 0.937, 0.937]
show spheres, prot and resi 341
color col_ptm_341, prot and resi 341
set_color col_ptm_344, [0.948, 0.948, 1.000]
show spheres, prot and resi 344
color col_ptm_344, prot and resi 344
set_color col_ptm_588, [1.000, 0.936, 0.936]
show spheres, prot and resi 588
color col_ptm_588, prot and resi 588
set_color col_ptm_591, [0.698, 0.698, 1.000]
show spheres, prot and resi 591
color col_ptm_591, prot and resi 591
set_color col_ptm_666, [0.807, 0.807, 1.000]
show spheres, prot and resi 666
color col_ptm_666, prot and resi 666
set_color col_ptm_642, [1.000, 0.987, 0.987]
show spheres, prot and resi 642
color col_ptm_642, prot and resi 642
set_color col_ptm_341, [1.000, 0.929, 0.929]
show spheres, prot and resi 341
color col_ptm_341, prot and resi 341
set_color col_ptm_344, [0.915, 0.915, 1.000]
show spheres, prot and resi 344
color col_ptm_344, prot and resi 344
set_color col_ptm_588, [0.817, 0.817, 1.000]
show spheres, prot and resi 588
color col_ptm_588, prot and resi 588
set_color col_ptm_591, [0.410, 0.410, 1.000]
show spheres, prot and resi 591
color col_ptm_591, prot and resi 591
label prot and resi 591 and name CA, "S591 (log2FC=-1.18)"
set_color col_ptm_666, [0.647, 0.647, 1.000]
show spheres, prot and resi 666
color col_ptm_666, prot and resi 666
label prot and resi 666 and name CA, "S666 (log2FC=-0.71)"
set_color col_ptm_642, [0.955, 0.955, 1.000]
show spheres, prot and resi 642
color col_ptm_642, prot and resi 642
set_color col_ptm_341, [0.969, 0.969, 1.000]
show spheres, prot and resi 341
color col_ptm_341, prot and resi 341
set_color col_ptm_344, [0.939, 0.939, 1.000]
show spheres, prot and resi 344
color col_ptm_344, prot and resi 344
set_color col_ptm_588, [1.000, 0.000, 0.000]
show spheres, prot and resi 588
color col_ptm_588, prot and resi 588
label prot and resi 588 and name CA, "S588 (log2FC=+2.01)"
set_color col_ptm_591, [0.343, 0.343, 1.000]
show spheres, prot and resi 591
color col_ptm_591, prot and resi 591
label prot and resi 591 and name CA, "S591 (log2FC=-1.31)"
set_color col_ptm_666, [1.000, 0.850, 0.850]
show spheres, prot and resi 666
color col_ptm_666, prot and resi 666
set_color col_ptm_642, [1.000, 0.539, 0.539]
show spheres, prot and resi 642
color col_ptm_642, prot and resi 642
label prot and resi 642 and name CA, "T642 (log2FC=+0.92)"
set_color col_ptm_341, [0.987, 0.987, 1.000]
show spheres, prot and resi 341
color col_ptm_341, prot and resi 341
set_color col_ptm_344, [1.000, 0.992, 0.992]
show spheres, prot and resi 344
color col_ptm_344, prot and resi 344
set_color col_ptm_588, [1.000, 0.963, 0.963]
show spheres, prot and resi 588
color col_ptm_588, prot and resi 588
set_color col_ptm_591, [0.820, 0.820, 1.000]
show spheres, prot and resi 591
color col_ptm_591, prot and resi 591
set_color col_ptm_666, [1.000, 0.909, 0.909]
show spheres, prot and resi 666
color col_ptm_666, prot and resi 666
set_color col_ptm_642, [1.000, 0.985, 0.985]
show spheres, prot and resi 642
color col_ptm_642, prot and resi 642
set_color col_ptm_341, [1.000, 0.992, 0.992]
show spheres, prot and resi 341
color col_ptm_341, prot and resi 341
set_color col_ptm_344, [0.967, 0.967, 1.000]
show spheres, prot and resi 344
color col_ptm_344, prot and resi 344
set_color col_ptm_588, [0.753, 0.753, 1.000]
show spheres, prot and resi 588
color col_ptm_588, prot and resi 588
set_color col_ptm_591, [0.712, 0.712, 1.000]
show spheres, prot and resi 591
color col_ptm_591, prot and resi 591
set_color col_ptm_666, [0.841, 0.841, 1.000]
show spheres, prot and resi 666
color col_ptm_666, prot and resi 666
set_color col_ptm_642, [0.942, 0.942, 1.000]
show spheres, prot and resi 642
color col_ptm_642, prot and resi 642
set_color col_ptm_341, [0.990, 0.990, 1.000]
show spheres, prot and resi 341
color col_ptm_341, prot and resi 341
set_color col_ptm_344, [0.899, 0.899, 1.000]
show spheres, prot and resi 344
color col_ptm_344, prot and resi 344
set_color col_ptm_588, [1.000, 0.279, 0.279]
show spheres, prot and resi 588
color col_ptm_588, prot and resi 588
label prot and resi 588 and name CA, "S588 (log2FC=+1.44)"
set_color col_ptm_591, [0.235, 0.235, 1.000]
show spheres, prot and resi 591
color col_ptm_591, prot and resi 591
label prot and resi 591 and name CA, "S591 (log2FC=-1.53)"
set_color col_ptm_666, [0.900, 0.900, 1.000]
show spheres, prot and resi 666
color col_ptm_666, prot and resi 666
set_color col_ptm_642, [1.000, 0.613, 0.613]
show spheres, prot and resi 642
color col_ptm_642, prot and resi 642
set_color col_ptm_341, [0.937, 0.937, 1.000]
show spheres, prot and resi 341
color col_ptm_341, prot and resi 341
set_color col_ptm_344, [1.000, 0.948, 0.948]
show spheres, prot and resi 344
color col_ptm_344, prot and resi 344
set_color col_ptm_588, [0.936, 0.936, 1.000]
show spheres, prot and resi 588
color col_ptm_588, prot and resi 588
set_color col_ptm_591, [1.000, 0.698, 0.698]
show spheres, prot and resi 591
color col_ptm_591, prot and resi 591
set_color col_ptm_666, [1.000, 0.807, 0.807]
show spheres, prot and resi 666
color col_ptm_666, prot and resi 666
set_color col_ptm_642, [0.987, 0.987, 1.000]
show spheres, prot and resi 642
color col_ptm_642, prot and resi 642
set_color col_ptm_341, [1.000, 0.992, 0.992]
show spheres, prot and resi 341
color col_ptm_341, prot and resi 341
set_color col_ptm_344, [0.966, 0.966, 1.000]
show spheres, prot and resi 344
color col_ptm_344, prot and resi 344
set_color col_ptm_588, [1.000, 0.906, 0.906]
show spheres, prot and resi 588
color col_ptm_588, prot and resi 588
set_color col_ptm_591, [0.626, 0.626, 1.000]
show spheres, prot and resi 591
color col_ptm_591, prot and resi 591
set_color col_ptm_666, [0.900, 0.900, 1.000]
show spheres, prot and resi 666
color col_ptm_666, prot and resi 666
set_color col_ptm_642, [1.000, 0.965, 0.965]
show spheres, prot and resi 642
color col_ptm_642, prot and resi 642
set_color col_ptm_341, [1.000, 0.973, 0.973]
show spheres, prot and resi 341
color col_ptm_341, prot and resi 341
set_color col_ptm_344, [1.000, 0.937, 0.937]
show spheres, prot and resi 344
color col_ptm_344, prot and resi 344
set_color col_ptm_588, [0.122, 0.122, 1.000]
show spheres, prot and resi 588
color col_ptm_588, prot and resi 588
label prot and resi 588 and name CA, "S588 (log2FC=-1.76)"
set_color col_ptm_591, [1.000, 0.431, 0.431]
show spheres, prot and resi 591
color col_ptm_591, prot and resi 591
label prot and resi 591 and name CA, "S591 (log2FC=+1.14)"
set_color col_ptm_666, [0.900, 0.900, 1.000]
show spheres, prot and resi 666
color col_ptm_666, prot and resi 666
set_color col_ptm_642, [0.576, 0.576, 1.000]
show spheres, prot and resi 642
color col_ptm_642, prot and resi 642
label prot and resi 642 and name CA, "T642 (log2FC=-0.85)"

set label_size, 16
set label_color, black
set label_font_id, 7
set sphere_scale, 0.8
orient prot
zoom prot, 5
ray 2000, 1500
# save output_3d/TBC1D4_O60343_pymol.png