# PyMOL Visualization Script for TPR (Comparison)
# Generated by ptm3d Visualizer
reinitialize
bg_color white
load "/Users/jonasgrossmann/GitHub/PTMvisualizer/output_3d/structures/P12270.pdb", prot
hide everything, prot
show cartoon, prot
color gray80, prot

# Set up log2FC color spectrum
set b_factor_min, -2.0
set b_factor_max, 2.0

# Assign log2FC values to PTM residues
set_color col_ptm_1185, [1.000, 0.936, 0.936]
show spheres, prot and resi 1185
color col_ptm_1185, prot and resi 1185
set_color col_ptm_1838, [0.940, 0.940, 1.000]
show spheres, prot and resi 1838
color col_ptm_1838, prot and resi 1838
set_color col_ptm_2037, [1.000, 0.773, 0.773]
show spheres, prot and resi 2037
color col_ptm_2037, prot and resi 2037
set_color col_ptm_2048, [1.000, 0.905, 0.905]
show spheres, prot and resi 2048
color col_ptm_2048, prot and resi 2048
set_color col_ptm_2061, [1.000, 0.958, 0.958]
show spheres, prot and resi 2061
color col_ptm_2061, prot and resi 2061
set_color col_ptm_2073, [1.000, 0.983, 0.983]
show spheres, prot and resi 2073
color col_ptm_2073, prot and resi 2073
set_color col_ptm_2155, [1.000, 0.200, 0.200]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
label prot and resi 2155 and name CA, "S2155 (log2FC=+1.60)"
set_color col_ptm_379, [1.000, 0.968, 0.968]
show spheres, prot and resi 379
color col_ptm_379, prot and resi 379
set_color col_ptm_523, [1.000, 0.857, 0.857]
show spheres, prot and resi 523
color col_ptm_523, prot and resi 523
set_color col_ptm_62, [1.000, 0.930, 0.930]
show spheres, prot and resi 62
color col_ptm_62, prot and resi 62
set_color col_ptm_64, [0.990, 0.990, 1.000]
show spheres, prot and resi 64
color col_ptm_64, prot and resi 64
set_color col_ptm_1650, [1.000, 0.968, 0.968]
show spheres, prot and resi 1650
color col_ptm_1650, prot and resi 1650
set_color col_ptm_1850, [1.000, 0.923, 0.923]
show spheres, prot and resi 1850
color col_ptm_1850, prot and resi 1850
set_color col_ptm_2116, [1.000, 0.434, 0.434]
show spheres, prot and resi 2116
color col_ptm_2116, prot and resi 2116
label prot and resi 2116 and name CA, "T2116 (log2FC=+1.13)"
set_color col_ptm_2137, [1.000, 0.388, 0.388]
show spheres, prot and resi 2137
color col_ptm_2137, prot and resi 2137
label prot and resi 2137 and name CA, "T2137 (log2FC=+1.22)"
set_color col_ptm_381, [1.000, 0.986, 0.986]
show spheres, prot and resi 381
color col_ptm_381, prot and resi 381
set_color col_ptm_1185, [1.000, 0.997, 0.997]
show spheres, prot and resi 1185
color col_ptm_1185, prot and resi 1185
set_color col_ptm_1838, [0.901, 0.901, 1.000]
show spheres, prot and resi 1838
color col_ptm_1838, prot and resi 1838
set_color col_ptm_2037, [1.000, 0.696, 0.696]
show spheres, prot and resi 2037
color col_ptm_2037, prot and resi 2037
set_color col_ptm_2048, [1.000, 0.873, 0.873]
show spheres, prot and resi 2048
color col_ptm_2048, prot and resi 2048
set_color col_ptm_2061, [1.000, 0.854, 0.854]
show spheres, prot and resi 2061
color col_ptm_2061, prot and resi 2061
set_color col_ptm_2073, [0.993, 0.993, 1.000]
show spheres, prot and resi 2073
color col_ptm_2073, prot and resi 2073
set_color col_ptm_2155, [1.000, 0.979, 0.979]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_379, [1.000, 0.931, 0.931]
show spheres, prot and resi 379
color col_ptm_379, prot and resi 379
set_color col_ptm_523, [1.000, 0.981, 0.981]
show spheres, prot and resi 523
color col_ptm_523, prot and resi 523
set_color col_ptm_62, [0.956, 0.956, 1.000]
show spheres, prot and resi 62
color col_ptm_62, prot and resi 62
set_color col_ptm_64, [0.978, 0.978, 1.000]
show spheres, prot and resi 64
color col_ptm_64, prot and resi 64
set_color col_ptm_1650, [0.963, 0.963, 1.000]
show spheres, prot and resi 1650
color col_ptm_1650, prot and resi 1650
set_color col_ptm_1850, [1.000, 0.994, 0.994]
show spheres, prot and resi 1850
color col_ptm_1850, prot and resi 1850
set_color col_ptm_2116, [1.000, 0.940, 0.940]
show spheres, prot and resi 2116
color col_ptm_2116, prot and resi 2116
set_color col_ptm_2137, [1.000, 0.997, 0.997]
show spheres, prot and resi 2137
color col_ptm_2137, prot and resi 2137
set_color col_ptm_381, [0.996, 0.996, 1.000]
show spheres, prot and resi 381
color col_ptm_381, prot and resi 381
set_color col_ptm_1185, [0.994, 0.994, 1.000]
show spheres, prot and resi 1185
color col_ptm_1185, prot and resi 1185
set_color col_ptm_1838, [0.888, 0.888, 1.000]
show spheres, prot and resi 1838
color col_ptm_1838, prot and resi 1838
set_color col_ptm_2037, [1.000, 0.951, 0.951]
show spheres, prot and resi 2037
color col_ptm_2037, prot and resi 2037
set_color col_ptm_2048, [1.000, 0.905, 0.905]
show spheres, prot and resi 2048
color col_ptm_2048, prot and resi 2048
set_color col_ptm_2061, [1.000, 0.935, 0.935]
show spheres, prot and resi 2061
color col_ptm_2061, prot and resi 2061
set_color col_ptm_2073, [0.989, 0.989, 1.000]
show spheres, prot and resi 2073
color col_ptm_2073, prot and resi 2073
set_color col_ptm_2155, [1.000, 0.964, 0.964]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_379, [0.987, 0.987, 1.000]
show spheres, prot and resi 379
color col_ptm_379, prot and resi 379
set_color col_ptm_523, [1.000, 0.904, 0.904]
show spheres, prot and resi 523
color col_ptm_523, prot and resi 523
set_color col_ptm_62, [1.000, 0.996, 0.996]
show spheres, prot and resi 62
color col_ptm_62, prot and resi 62
set_color col_ptm_64, [0.939, 0.939, 1.000]
show spheres, prot and resi 64
color col_ptm_64, prot and resi 64
set_color col_ptm_1650, [0.932, 0.932, 1.000]
show spheres, prot and resi 1650
color col_ptm_1650, prot and resi 1650
set_color col_ptm_1850, [0.973, 0.973, 1.000]
show spheres, prot and resi 1850
color col_ptm_1850, prot and resi 1850
set_color col_ptm_2116, [0.932, 0.932, 1.000]
show spheres, prot and resi 2116
color col_ptm_2116, prot and resi 2116
set_color col_ptm_2137, [0.935, 0.935, 1.000]
show spheres, prot and resi 2137
color col_ptm_2137, prot and resi 2137
set_color col_ptm_381, [1.000, 1.000, 1.000]
show spheres, prot and resi 381
color col_ptm_381, prot and resi 381
set_color col_ptm_1185, [0.968, 0.968, 1.000]
show spheres, prot and resi 1185
color col_ptm_1185, prot and resi 1185
set_color col_ptm_1838, [0.860, 0.860, 1.000]
show spheres, prot and resi 1838
color col_ptm_1838, prot and resi 1838
set_color col_ptm_2037, [0.916, 0.916, 1.000]
show spheres, prot and resi 2037
color col_ptm_2037, prot and resi 2037
set_color col_ptm_2048, [1.000, 0.880, 0.880]
show spheres, prot and resi 2048
color col_ptm_2048, prot and resi 2048
set_color col_ptm_2061, [1.000, 0.872, 0.872]
show spheres, prot and resi 2061
color col_ptm_2061, prot and resi 2061
set_color col_ptm_2073, [0.994, 0.994, 1.000]
show spheres, prot and resi 2073
color col_ptm_2073, prot and resi 2073
set_color col_ptm_2155, [1.000, 0.977, 0.977]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_379, [0.994, 0.994, 1.000]
show spheres, prot and resi 379
color col_ptm_379, prot and resi 379
set_color col_ptm_523, [0.676, 0.676, 1.000]
show spheres, prot and resi 523
color col_ptm_523, prot and resi 523
set_color col_ptm_62, [0.927, 0.927, 1.000]
show spheres, prot and resi 62
color col_ptm_62, prot and resi 62
set_color col_ptm_64, [0.970, 0.970, 1.000]
show spheres, prot and resi 64
color col_ptm_64, prot and resi 64
set_color col_ptm_1650, [0.938, 0.938, 1.000]
show spheres, prot and resi 1650
color col_ptm_1650, prot and resi 1650
set_color col_ptm_1850, [1.000, 0.947, 0.947]
show spheres, prot and resi 1850
color col_ptm_1850, prot and resi 1850
set_color col_ptm_2116, [0.905, 0.905, 1.000]
show spheres, prot and resi 2116
color col_ptm_2116, prot and resi 2116
set_color col_ptm_2137, [1.000, 0.863, 0.863]
show spheres, prot and resi 2137
color col_ptm_2137, prot and resi 2137
set_color col_ptm_381, [0.978, 0.978, 1.000]
show spheres, prot and resi 381
color col_ptm_381, prot and resi 381
set_color col_ptm_1185, [0.750, 0.750, 1.000]
show spheres, prot and resi 1185
color col_ptm_1185, prot and resi 1185
label prot and resi 1185 and name CA, "S1185 (log2FC=-0.50)"
set_color col_ptm_1838, [0.832, 0.832, 1.000]
show spheres, prot and resi 1838
color col_ptm_1838, prot and resi 1838
set_color col_ptm_2037, [0.864, 0.864, 1.000]
show spheres, prot and resi 2037
color col_ptm_2037, prot and resi 2037
set_color col_ptm_2048, [0.825, 0.825, 1.000]
show spheres, prot and resi 2048
color col_ptm_2048, prot and resi 2048
set_color col_ptm_2061, [1.000, 0.739, 0.739]
show spheres, prot and resi 2061
color col_ptm_2061, prot and resi 2061
label prot and resi 2061 and name CA, "S2061 (log2FC=+0.52)"
set_color col_ptm_2073, [1.000, 0.978, 0.978]
show spheres, prot and resi 2073
color col_ptm_2073, prot and resi 2073
set_color col_ptm_2155, [0.828, 0.828, 1.000]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_379, [0.848, 0.848, 1.000]
show spheres, prot and resi 379
color col_ptm_379, prot and resi 379
set_color col_ptm_523, [0.619, 0.619, 1.000]
show spheres, prot and resi 523
color col_ptm_523, prot and resi 523
label prot and resi 523 and name CA, "S523 (log2FC=-0.76)"
set_color col_ptm_62, [0.991, 0.991, 1.000]
show spheres, prot and resi 62
color col_ptm_62, prot and resi 62
set_color col_ptm_64, [0.838, 0.838, 1.000]
show spheres, prot and resi 64
color col_ptm_64, prot and resi 64
set_color col_ptm_1650, [0.734, 0.734, 1.000]
show spheres, prot and resi 1650
color col_ptm_1650, prot and resi 1650
label prot and resi 1650 and name CA, "T1650 (log2FC=-0.53)"
set_color col_ptm_1850, [0.767, 0.767, 1.000]
show spheres, prot and resi 1850
color col_ptm_1850, prot and resi 1850
label prot and resi 1850 and name CA, "T1850 (log2FC=-0.47)"
set_color col_ptm_2116, [0.577, 0.577, 1.000]
show spheres, prot and resi 2116
color col_ptm_2116, prot and resi 2116
label prot and resi 2116 and name CA, "T2116 (log2FC=-0.85)"
set_color col_ptm_2137, [0.836, 0.836, 1.000]
show spheres, prot and resi 2137
color col_ptm_2137, prot and resi 2137
set_color col_ptm_381, [0.719, 0.719, 1.000]
show spheres, prot and resi 381
color col_ptm_381, prot and resi 381
set_color col_ptm_1185, [1.000, 0.970, 0.970]
show spheres, prot and resi 1185
color col_ptm_1185, prot and resi 1185
set_color col_ptm_1838, [0.899, 0.899, 1.000]
show spheres, prot and resi 1838
color col_ptm_1838, prot and resi 1838
set_color col_ptm_2037, [0.838, 0.838, 1.000]
show spheres, prot and resi 2037
color col_ptm_2037, prot and resi 2037
set_color col_ptm_2048, [1.000, 0.912, 0.912]
show spheres, prot and resi 2048
color col_ptm_2048, prot and resi 2048
set_color col_ptm_2061, [1.000, 0.975, 0.975]
show spheres, prot and resi 2061
color col_ptm_2061, prot and resi 2061
set_color col_ptm_2073, [1.000, 0.982, 0.982]
show spheres, prot and resi 2073
color col_ptm_2073, prot and resi 2073
set_color col_ptm_2155, [1.000, 0.198, 0.198]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
label prot and resi 2155 and name CA, "S2155 (log2FC=+1.60)"
set_color col_ptm_379, [0.958, 0.958, 1.000]
show spheres, prot and resi 379
color col_ptm_379, prot and resi 379
set_color col_ptm_523, [0.800, 0.800, 1.000]
show spheres, prot and resi 523
color col_ptm_523, prot and resi 523
set_color col_ptm_62, [1.000, 0.959, 0.959]
show spheres, prot and resi 62
color col_ptm_62, prot and resi 62
set_color col_ptm_64, [0.983, 0.983, 1.000]
show spheres, prot and resi 64
color col_ptm_64, prot and resi 64
set_color col_ptm_1650, [1.000, 0.994, 0.994]
show spheres, prot and resi 1650
color col_ptm_1650, prot and resi 1650
set_color col_ptm_1850, [1.000, 0.876, 0.876]
show spheres, prot and resi 1850
color col_ptm_1850, prot and resi 1850
set_color col_ptm_2116, [1.000, 0.589, 0.589]
show spheres, prot and resi 2116
color col_ptm_2116, prot and resi 2116
label prot and resi 2116 and name CA, "T2116 (log2FC=+0.82)"
set_color col_ptm_2137, [1.000, 0.255, 0.255]
show spheres, prot and resi 2137
color col_ptm_2137, prot and resi 2137
label prot and resi 2137 and name CA, "T2137 (log2FC=+1.49)"
set_color col_ptm_381, [0.996, 0.996, 1.000]
show spheres, prot and resi 381
color col_ptm_381, prot and resi 381
set_color col_ptm_1185, [0.991, 0.991, 1.000]
show spheres, prot and resi 1185
color col_ptm_1185, prot and resi 1185
set_color col_ptm_1838, [0.987, 0.987, 1.000]
show spheres, prot and resi 1838
color col_ptm_1838, prot and resi 1838
set_color col_ptm_2037, [0.744, 0.744, 1.000]
show spheres, prot and resi 2037
color col_ptm_2037, prot and resi 2037
set_color col_ptm_2048, [0.968, 0.968, 1.000]
show spheres, prot and resi 2048
color col_ptm_2048, prot and resi 2048
set_color col_ptm_2061, [0.920, 0.920, 1.000]
show spheres, prot and resi 2061
color col_ptm_2061, prot and resi 2061
set_color col_ptm_2073, [0.996, 0.996, 1.000]
show spheres, prot and resi 2073
color col_ptm_2073, prot and resi 2073
set_color col_ptm_2155, [1.000, 0.985, 0.985]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_379, [0.918, 0.918, 1.000]
show spheres, prot and resi 379
color col_ptm_379, prot and resi 379
set_color col_ptm_523, [1.000, 0.923, 0.923]
show spheres, prot and resi 523
color col_ptm_523, prot and resi 523
set_color col_ptm_62, [1.000, 0.952, 0.952]
show spheres, prot and resi 62
color col_ptm_62, prot and resi 62
set_color col_ptm_64, [0.961, 0.961, 1.000]
show spheres, prot and resi 64
color col_ptm_64, prot and resi 64
set_color col_ptm_1650, [0.969, 0.969, 1.000]
show spheres, prot and resi 1650
color col_ptm_1650, prot and resi 1650
set_color col_ptm_1850, [0.967, 0.967, 1.000]
show spheres, prot and resi 1850
color col_ptm_1850, prot and resi 1850
set_color col_ptm_2116, [0.872, 0.872, 1.000]
show spheres, prot and resi 2116
color col_ptm_2116, prot and resi 2116
set_color col_ptm_2137, [0.932, 0.932, 1.000]
show spheres, prot and resi 2137
color col_ptm_2137, prot and resi 2137
set_color col_ptm_381, [1.000, 0.996, 0.996]
show spheres, prot and resi 381
color col_ptm_381, prot and resi 381
set_color col_ptm_1185, [0.782, 0.782, 1.000]
show spheres, prot and resi 1185
color col_ptm_1185, prot and resi 1185
set_color col_ptm_1838, [0.972, 0.972, 1.000]
show spheres, prot and resi 1838
color col_ptm_1838, prot and resi 1838
set_color col_ptm_2037, [0.948, 0.948, 1.000]
show spheres, prot and resi 2037
color col_ptm_2037, prot and resi 2037
set_color col_ptm_2048, [0.706, 0.706, 1.000]
show spheres, prot and resi 2048
color col_ptm_2048, prot and resi 2048
set_color col_ptm_2061, [1.000, 0.867, 0.867]
show spheres, prot and resi 2061
color col_ptm_2061, prot and resi 2061
set_color col_ptm_2073, [1.000, 0.972, 0.972]
show spheres, prot and resi 2073
color col_ptm_2073, prot and resi 2073
set_color col_ptm_2155, [0.805, 0.805, 1.000]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_379, [0.853, 0.853, 1.000]
show spheres, prot and resi 379
color col_ptm_379, prot and resi 379
set_color col_ptm_523, [0.943, 0.943, 1.000]
show spheres, prot and resi 523
color col_ptm_523, prot and resi 523
set_color col_ptm_62, [1.000, 0.935, 0.935]
show spheres, prot and resi 62
color col_ptm_62, prot and resi 62
set_color col_ptm_64, [0.868, 0.868, 1.000]
show spheres, prot and resi 64
color col_ptm_64, prot and resi 64
set_color col_ptm_1650, [0.796, 0.796, 1.000]
show spheres, prot and resi 1650
color col_ptm_1650, prot and resi 1650
set_color col_ptm_1850, [0.713, 0.713, 1.000]
show spheres, prot and resi 1850
color col_ptm_1850, prot and resi 1850
set_color col_ptm_2116, [0.672, 0.672, 1.000]
show spheres, prot and resi 2116
color col_ptm_2116, prot and resi 2116
set_color col_ptm_2137, [0.699, 0.699, 1.000]
show spheres, prot and resi 2137
color col_ptm_2137, prot and resi 2137
set_color col_ptm_381, [0.741, 0.741, 1.000]
show spheres, prot and resi 381
color col_ptm_381, prot and resi 381
set_color col_ptm_1185, [0.821, 0.821, 1.000]
show spheres, prot and resi 1185
color col_ptm_1185, prot and resi 1185
set_color col_ptm_1838, [0.883, 0.883, 1.000]
show spheres, prot and resi 1838
color col_ptm_1838, prot and resi 1838
set_color col_ptm_2037, [1.000, 0.958, 0.958]
show spheres, prot and resi 2037
color col_ptm_2037, prot and resi 2037
set_color col_ptm_2048, [0.825, 0.825, 1.000]
show spheres, prot and resi 2048
color col_ptm_2048, prot and resi 2048
set_color col_ptm_2061, [1.000, 0.762, 0.762]
show spheres, prot and resi 2061
color col_ptm_2061, prot and resi 2061
set_color col_ptm_2073, [1.000, 0.950, 0.950]
show spheres, prot and resi 2073
color col_ptm_2073, prot and resi 2073
set_color col_ptm_2155, [1.000, 0.408, 0.408]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
label prot and resi 2155 and name CA, "S2155 (log2FC=+1.18)"
set_color col_ptm_379, [0.893, 0.893, 1.000]
show spheres, prot and resi 379
color col_ptm_379, prot and resi 379
set_color col_ptm_523, [0.666, 0.666, 1.000]
show spheres, prot and resi 523
color col_ptm_523, prot and resi 523
set_color col_ptm_62, [1.000, 0.942, 0.942]
show spheres, prot and resi 62
color col_ptm_62, prot and resi 62
set_color col_ptm_64, [0.889, 0.889, 1.000]
show spheres, prot and resi 64
color col_ptm_64, prot and resi 64
set_color col_ptm_1650, [0.833, 0.833, 1.000]
show spheres, prot and resi 1650
color col_ptm_1650, prot and resi 1650
set_color col_ptm_1850, [0.871, 0.871, 1.000]
show spheres, prot and resi 1850
color col_ptm_1850, prot and resi 1850
set_color col_ptm_2116, [1.000, 0.788, 0.788]
show spheres, prot and resi 2116
color col_ptm_2116, prot and resi 2116
set_color col_ptm_2137, [1.000, 0.488, 0.488]
show spheres, prot and resi 2137
color col_ptm_2137, prot and resi 2137
label prot and resi 2137 and name CA, "T2137 (log2FC=+1.02)"
set_color col_ptm_381, [0.732, 0.732, 1.000]
show spheres, prot and resi 381
color col_ptm_381, prot and resi 381
set_color col_ptm_1185, [1.000, 0.968, 0.968]
show spheres, prot and resi 1185
color col_ptm_1185, prot and resi 1185
set_color col_ptm_1838, [1.000, 0.860, 0.860]
show spheres, prot and resi 1838
color col_ptm_1838, prot and resi 1838
set_color col_ptm_2037, [1.000, 0.916, 0.916]
show spheres, prot and resi 2037
color col_ptm_2037, prot and resi 2037
set_color col_ptm_2048, [0.880, 0.880, 1.000]
show spheres, prot and resi 2048
color col_ptm_2048, prot and resi 2048
set_color col_ptm_2061, [0.872, 0.872, 1.000]
show spheres, prot and resi 2061
color col_ptm_2061, prot and resi 2061
set_color col_ptm_2073, [1.000, 0.994, 0.994]
show spheres, prot and resi 2073
color col_ptm_2073, prot and resi 2073
set_color col_ptm_2155, [0.977, 0.977, 1.000]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_379, [1.000, 0.994, 0.994]
show spheres, prot and resi 379
color col_ptm_379, prot and resi 379
set_color col_ptm_523, [1.000, 0.676, 0.676]
show spheres, prot and resi 523
color col_ptm_523, prot and resi 523
set_color col_ptm_62, [1.000, 0.927, 0.927]
show spheres, prot and resi 62
color col_ptm_62, prot and resi 62
set_color col_ptm_64, [1.000, 0.970, 0.970]
show spheres, prot and resi 64
color col_ptm_64, prot and resi 64
set_color col_ptm_1650, [1.000, 0.938, 0.938]
show spheres, prot and resi 1650
color col_ptm_1650, prot and resi 1650
set_color col_ptm_1850, [0.947, 0.947, 1.000]
show spheres, prot and resi 1850
color col_ptm_1850, prot and resi 1850
set_color col_ptm_2116, [1.000, 0.905, 0.905]
show spheres, prot and resi 2116
color col_ptm_2116, prot and resi 2116
set_color col_ptm_2137, [0.863, 0.863, 1.000]
show spheres, prot and resi 2137
color col_ptm_2137, prot and resi 2137
set_color col_ptm_381, [1.000, 0.978, 0.978]
show spheres, prot and resi 381
color col_ptm_381, prot and resi 381
set_color col_ptm_1185, [0.965, 0.965, 1.000]
show spheres, prot and resi 1185
color col_ptm_1185, prot and resi 1185
set_color col_ptm_1838, [0.959, 0.959, 1.000]
show spheres, prot and resi 1838
color col_ptm_1838, prot and resi 1838
set_color col_ptm_2037, [0.611, 0.611, 1.000]
show spheres, prot and resi 2037
color col_ptm_2037, prot and resi 2037
set_color col_ptm_2048, [0.993, 0.993, 1.000]
show spheres, prot and resi 2048
color col_ptm_2048, prot and resi 2048
set_color col_ptm_2061, [0.982, 0.982, 1.000]
show spheres, prot and resi 2061
color col_ptm_2061, prot and resi 2061
set_color col_ptm_2073, [1.000, 1.000, 1.000]
show spheres, prot and resi 2073
color col_ptm_2073, prot and resi 2073
set_color col_ptm_2155, [1.000, 0.998, 0.998]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
set_color col_ptm_379, [0.926, 0.926, 1.000]
show spheres, prot and resi 379
color col_ptm_379, prot and resi 379
set_color col_ptm_523, [0.657, 0.657, 1.000]
show spheres, prot and resi 523
color col_ptm_523, prot and resi 523
set_color col_ptm_62, [0.971, 0.971, 1.000]
show spheres, prot and resi 62
color col_ptm_62, prot and resi 62
set_color col_ptm_64, [0.993, 0.993, 1.000]
show spheres, prot and resi 64
color col_ptm_64, prot and resi 64
set_color col_ptm_1650, [0.974, 0.974, 1.000]
show spheres, prot and resi 1650
color col_ptm_1650, prot and resi 1650
set_color col_ptm_1850, [1.000, 0.953, 0.953]
show spheres, prot and resi 1850
color col_ptm_1850, prot and resi 1850
set_color col_ptm_2116, [0.845, 0.845, 1.000]
show spheres, prot and resi 2116
color col_ptm_2116, prot and resi 2116
set_color col_ptm_2137, [1.000, 0.866, 0.866]
show spheres, prot and resi 2137
color col_ptm_2137, prot and resi 2137
set_color col_ptm_381, [0.982, 0.982, 1.000]
show spheres, prot and resi 381
color col_ptm_381, prot and resi 381
set_color col_ptm_1185, [1.000, 0.971, 0.971]
show spheres, prot and resi 1185
color col_ptm_1185, prot and resi 1185
set_color col_ptm_1838, [1.000, 0.907, 0.907]
show spheres, prot and resi 1838
color col_ptm_1838, prot and resi 1838
set_color col_ptm_2037, [0.965, 0.965, 1.000]
show spheres, prot and resi 2037
color col_ptm_2037, prot and resi 2037
set_color col_ptm_2048, [0.998, 0.998, 1.000]
show spheres, prot and resi 2048
color col_ptm_2048, prot and resi 2048
set_color col_ptm_2061, [0.899, 0.899, 1.000]
show spheres, prot and resi 2061
color col_ptm_2061, prot and resi 2061
set_color col_ptm_2073, [0.972, 0.972, 1.000]
show spheres, prot and resi 2073
color col_ptm_2073, prot and resi 2073
set_color col_ptm_2155, [0.269, 0.269, 1.000]
show spheres, prot and resi 2155
color col_ptm_2155, prot and resi 2155
label prot and resi 2155 and name CA, "S2155 (log2FC=-1.46)"
set_color col_ptm_379, [1.000, 0.961, 0.961]
show spheres, prot and resi 379
color col_ptm_379, prot and resi 379
set_color col_ptm_523, [1.000, 0.870, 0.870]
show spheres, prot and resi 523
color col_ptm_523, prot and resi 523
set_color col_ptm_62, [0.944, 0.944, 1.000]
show spheres, prot and resi 62
color col_ptm_62, prot and resi 62
set_color col_ptm_64, [1.000, 0.954, 0.954]
show spheres, prot and resi 64
color col_ptm_64, prot and resi 64
set_color col_ptm_1650, [1.000, 0.957, 0.957]
show spheres, prot and resi 1650
color col_ptm_1650, prot and resi 1650
set_color col_ptm_1850, [0.976, 0.976, 1.000]
show spheres, prot and resi 1850
color col_ptm_1850, prot and resi 1850
set_color col_ptm_2116, [0.603, 0.603, 1.000]
show spheres, prot and resi 2116
color col_ptm_2116, prot and resi 2116
label prot and resi 2116 and name CA, "T2116 (log2FC=-0.79)"
set_color col_ptm_2137, [0.377, 0.377, 1.000]
show spheres, prot and resi 2137
color col_ptm_2137, prot and resi 2137
label prot and resi 2137 and name CA, "T2137 (log2FC=-1.25)"
set_color col_ptm_381, [1.000, 0.914, 0.914]
show spheres, prot and resi 381
color col_ptm_381, prot and resi 381

set label_size, 16
set label_color, black
set label_font_id, 7
set sphere_scale, 0.8
orient prot
zoom prot, 5
ray 2000, 1500
# save output_3d/TPR_P12270_pymol.png