"""
pymol_exporter.py - Module for generating PyMOL scripts (.pml) and high-resolution 3D figures for publications.
"""

import os

def generate_pymol_script(pdb_path, ptm_df, output_pml_path, protein_name="Protein", contrast_name="Comparison"):
    """
    Generates a PyMOL script (.pml) to render 3D protein structure with PTM sites 
    colored by log2-fold-change (diff.site).
    """
    os.makedirs(os.path.dirname(os.path.abspath(output_pml_path)), exist_ok=True)
    abs_pdb_path = os.path.abspath(pdb_path)
    
    # Filter PTMs with valid residue positions
    valid_ptms = ptm_df.dropna(subset=['pos_in_protein', 'log2fc']).copy()
    
    lines = [
        f"# PyMOL Visualization Script for {protein_name} ({contrast_name})",
        f"# Generated by ptm3d Visualizer",
        "reinitialize",
        "bg_color white",
        f"load \"{abs_pdb_path}\", prot",
        "hide everything, prot",
        "show cartoon, prot",
        "color gray80, prot",
        ""
    ]
    
    # Define color scale definitions (Blue-White-Red gradient)
    lines.append("# Set up log2FC color spectrum")
    lines.append("set b_factor_min, -2.0")
    lines.append("set b_factor_max, 2.0")
    lines.append("")
    
    # Assign log2FC to b-factor property of modified residues
    lines.append("# Assign log2FC values to PTM residues")
    for idx, row in valid_ptms.iterrows():
        res_num = int(row['pos_in_protein'])
        log2fc = float(row['log2fc'])
        fdr = float(row.get('fdr', 1.0))
        mod_aa = str(row.get('mod_aa', ''))
        site_str = f"{mod_aa}{res_num}"
        
        # Color mapping logic
        # Blue for negative (down), Red for positive (up)
        if log2fc > 0:
            intensity = min(1.0, log2fc / 2.0)
            r, g, b = 1.0, 1.0 - intensity, 1.0 - intensity
        else:
            intensity = min(1.0, abs(log2fc) / 2.0)
            r, g, b = 1.0 - intensity, 1.0 - intensity, 1.0
            
        color_name = f"col_ptm_{res_num}"
        lines.append(f"set_color {color_name}, [{r:.3f}, {g:.3f}, {b:.3f}]")
        lines.append(f"show spheres, prot and resi {res_num}")
        lines.append(f"color {color_name}, prot and resi {res_num}")
        
        # Label significant sites (FDR < 0.05)
        if fdr < 0.05:
            lines.append(f"label prot and resi {res_num} and name CA, \"{site_str} (log2FC={log2fc:+.2f})\"")
            
    lines.extend([
        "",
        "set label_size, 16",
        "set label_color, black",
        "set label_font_id, 7",
        "set sphere_scale, 0.8",
        "orient prot",
        "zoom prot, 5",
        "ray 2000, 1500",
        f"# save {os.path.splitext(output_pml_path)[0]}.png"
    ])
    
    with open(output_pml_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))
        
    return output_pml_path
